<!DOCTYPE html>
<html lang="" xml:lang="">
<head>

  <meta charset="utf-8" />
  <meta http-equiv="X-UA-Compatible" content="IE=edge" />
  <title>Chapter 7 Inferential statistics, take 2 | R and RStudio for STAT216</title>
  <meta name="description" content="<p>These notes introduce the reader to R and RStudio following the rough structure
of STAT216 at FVCC.</p>" />
  <meta name="generator" content="bookdown 0.33 and GitBook 2.6.7" />

  <meta property="og:title" content="Chapter 7 Inferential statistics, take 2 | R and RStudio for STAT216" />
  <meta property="og:type" content="book" />
  
  <meta property="og:description" content="<p>These notes introduce the reader to R and RStudio following the rough structure
of STAT216 at FVCC.</p>" />
  <meta name="github-repo" content="rstudio/bookdown-demo" />

  <meta name="twitter:card" content="summary" />
  <meta name="twitter:title" content="Chapter 7 Inferential statistics, take 2 | R and RStudio for STAT216" />
  
  <meta name="twitter:description" content="<p>These notes introduce the reader to R and RStudio following the rough structure
of STAT216 at FVCC.</p>" />
  

<meta name="author" content="Charles Katerba" />



  <meta name="viewport" content="width=device-width, initial-scale=1" />
  <meta name="apple-mobile-web-app-capable" content="yes" />
  <meta name="apple-mobile-web-app-status-bar-style" content="black" />
  
  
<link rel="prev" href="inferential-statistics-take-1.html"/>
<link rel="next" href="modeling-relationships.html"/>
<script src="libs/jquery-3.6.0/jquery-3.6.0.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/fuse.js@6.4.6/dist/fuse.min.js"></script>
<link href="libs/gitbook-2.6.7/css/style.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-table.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-bookdown.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-highlight.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-search.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-fontsettings.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-clipboard.css" rel="stylesheet" />








<link href="libs/anchor-sections-1.1.0/anchor-sections.css" rel="stylesheet" />
<link href="libs/anchor-sections-1.1.0/anchor-sections-hash.css" rel="stylesheet" />
<script src="libs/anchor-sections-1.1.0/anchor-sections.js"></script>


<style type="text/css">
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
    color: #aaaaaa;
  }
pre.numberSource { margin-left: 3em; border-left: 1px solid #aaaaaa;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
code span.al { color: #ff0000; font-weight: bold; } /* Alert */
code span.an { color: #60a0b0; font-weight: bold; font-style: italic; } /* Annotation */
code span.at { color: #7d9029; } /* Attribute */
code span.bn { color: #40a070; } /* BaseN */
code span.bu { color: #008000; } /* BuiltIn */
code span.cf { color: #007020; font-weight: bold; } /* ControlFlow */
code span.ch { color: #4070a0; } /* Char */
code span.cn { color: #880000; } /* Constant */
code span.co { color: #60a0b0; font-style: italic; } /* Comment */
code span.cv { color: #60a0b0; font-weight: bold; font-style: italic; } /* CommentVar */
code span.do { color: #ba2121; font-style: italic; } /* Documentation */
code span.dt { color: #902000; } /* DataType */
code span.dv { color: #40a070; } /* DecVal */
code span.er { color: #ff0000; font-weight: bold; } /* Error */
code span.ex { } /* Extension */
code span.fl { color: #40a070; } /* Float */
code span.fu { color: #06287e; } /* Function */
code span.im { color: #008000; font-weight: bold; } /* Import */
code span.in { color: #60a0b0; font-weight: bold; font-style: italic; } /* Information */
code span.kw { color: #007020; font-weight: bold; } /* Keyword */
code span.op { color: #666666; } /* Operator */
code span.ot { color: #007020; } /* Other */
code span.pp { color: #bc7a00; } /* Preprocessor */
code span.sc { color: #4070a0; } /* SpecialChar */
code span.ss { color: #bb6688; } /* SpecialString */
code span.st { color: #4070a0; } /* String */
code span.va { color: #19177c; } /* Variable */
code span.vs { color: #4070a0; } /* VerbatimString */
code span.wa { color: #60a0b0; font-weight: bold; font-style: italic; } /* Warning */
</style>


<link rel="stylesheet" href="style.css" type="text/css" />
</head>

<body>



  <div class="book without-animation with-summary font-size-2 font-family-1" data-basepath=".">

    <div class="book-summary">
      <nav role="navigation">

<ul class="summary">
<li><a href="./">R for STAT216 @ FVCC</a></li>

<li class="divider"></li>
<li class="chapter" data-level="1" data-path="index.html"><a href="index.html"><i class="fa fa-check"></i><b>1</b> About</a>
<ul>
<li class="chapter" data-level="1.1" data-path="index.html"><a href="index.html#organization"><i class="fa fa-check"></i><b>1.1</b> Organization</a></li>
<li class="chapter" data-level="1.2" data-path="index.html"><a href="index.html#getting-started"><i class="fa fa-check"></i><b>1.2</b> Getting started</a></li>
<li class="chapter" data-level="1.3" data-path="index.html"><a href="index.html#code-in-this-book"><i class="fa fa-check"></i><b>1.3</b> Code in this book</a></li>
<li class="chapter" data-level="1.4" data-path="index.html"><a href="index.html#help"><i class="fa fa-check"></i><b>1.4</b> Help</a></li>
<li class="chapter" data-level="1.5" data-path="index.html"><a href="index.html#debugging"><i class="fa fa-check"></i><b>1.5</b> Debugging</a></li>
<li class="chapter" data-level="1.6" data-path="index.html"><a href="index.html#other-resources"><i class="fa fa-check"></i><b>1.6</b> Other resources</a></li>
</ul></li>
<li class="chapter" data-level="2" data-path="rstudio-basics.html"><a href="rstudio-basics.html"><i class="fa fa-check"></i><b>2</b> RStudio basics</a>
<ul>
<li class="chapter" data-level="2.1" data-path="rstudio-basics.html"><a href="rstudio-basics.html#a-big-calculator"><i class="fa fa-check"></i><b>2.1</b> A big calculator</a>
<ul>
<li class="chapter" data-level="2.1.1" data-path="rstudio-basics.html"><a href="rstudio-basics.html#numbers"><i class="fa fa-check"></i><b>2.1.1</b> Numbers</a></li>
<li class="chapter" data-level="2.1.2" data-path="rstudio-basics.html"><a href="rstudio-basics.html#strings"><i class="fa fa-check"></i><b>2.1.2</b> Strings</a></li>
<li class="chapter" data-level="2.1.3" data-path="rstudio-basics.html"><a href="rstudio-basics.html#logicals-and-logical-operators"><i class="fa fa-check"></i><b>2.1.3</b> Logicals and Logical operators</a></li>
</ul></li>
<li class="chapter" data-level="2.2" data-path="rstudio-basics.html"><a href="rstudio-basics.html#naming-things"><i class="fa fa-check"></i><b>2.2</b> Naming things</a></li>
<li class="chapter" data-level="2.3" data-path="rstudio-basics.html"><a href="rstudio-basics.html#lists-and-vectors"><i class="fa fa-check"></i><b>2.3</b> Lists and vectors</a>
<ul>
<li class="chapter" data-level="2.3.1" data-path="rstudio-basics.html"><a href="rstudio-basics.html#creating-lists"><i class="fa fa-check"></i><b>2.3.1</b> Creating lists</a></li>
<li class="chapter" data-level="2.3.2" data-path="rstudio-basics.html"><a href="rstudio-basics.html#subsetting-lists"><i class="fa fa-check"></i><b>2.3.2</b> Subsetting lists</a></li>
<li class="chapter" data-level="2.3.3" data-path="rstudio-basics.html"><a href="rstudio-basics.html#special-lists"><i class="fa fa-check"></i><b>2.3.3</b> Special lists</a></li>
<li class="chapter" data-level="2.3.4" data-path="rstudio-basics.html"><a href="rstudio-basics.html#list-arithmetic"><i class="fa fa-check"></i><b>2.3.4</b> List arithmetic</a></li>
</ul></li>
<li class="chapter" data-level="2.4" data-path="rstudio-basics.html"><a href="rstudio-basics.html#packages"><i class="fa fa-check"></i><b>2.4</b> Packages</a></li>
<li class="chapter" data-level="2.5" data-path="rstudio-basics.html"><a href="rstudio-basics.html#data-frames-and-tibbles"><i class="fa fa-check"></i><b>2.5</b> Data frames and tibbles</a>
<ul>
<li class="chapter" data-level="2.5.1" data-path="rstudio-basics.html"><a href="rstudio-basics.html#creating-data-frames"><i class="fa fa-check"></i><b>2.5.1</b> Creating data frames</a></li>
<li class="chapter" data-level="2.5.2" data-path="rstudio-basics.html"><a href="rstudio-basics.html#using-data-frames"><i class="fa fa-check"></i><b>2.5.2</b> Using data frames</a></li>
</ul></li>
<li class="chapter" data-level="2.6" data-path="rstudio-basics.html"><a href="rstudio-basics.html#r-markdown-documents"><i class="fa fa-check"></i><b>2.6</b> R Markdown documents</a></li>
</ul></li>
<li class="chapter" data-level="3" data-path="cross.html"><a href="cross.html"><i class="fa fa-check"></i><b>3</b> Summary statistics and data visualization</a>
<ul>
<li class="chapter" data-level="3.1" data-path="cross.html"><a href="cross.html#summary-statistics-in-r"><i class="fa fa-check"></i><b>3.1</b> Summary statistics in R</a>
<ul>
<li class="chapter" data-level="3.1.1" data-path="cross.html"><a href="cross.html#numerical-variables"><i class="fa fa-check"></i><b>3.1.1</b> Numerical variables</a></li>
<li class="chapter" data-level="3.1.2" data-path="cross.html"><a href="cross.html#categorical-variables"><i class="fa fa-check"></i><b>3.1.2</b> Categorical variables</a></li>
<li class="chapter" data-level="3.1.3" data-path="cross.html"><a href="cross.html#combining-it-all"><i class="fa fa-check"></i><b>3.1.3</b> Combining it all</a></li>
</ul></li>
<li class="chapter" data-level="3.2" data-path="cross.html"><a href="cross.html#data-visualization"><i class="fa fa-check"></i><b>3.2</b> Data visualization</a>
<ul>
<li class="chapter" data-level="3.2.1" data-path="cross.html"><a href="cross.html#base-r"><i class="fa fa-check"></i><b>3.2.1</b> Base R</a></li>
<li class="chapter" data-level="3.2.2" data-path="cross.html"><a href="cross.html#ggplot2"><i class="fa fa-check"></i><b>3.2.2</b> <code>ggplot2</code></a></li>
<li class="chapter" data-level="3.2.3" data-path="cross.html"><a href="cross.html#saving-plots"><i class="fa fa-check"></i><b>3.2.3</b> Saving plots</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="4" data-path="wrangling-data.html"><a href="wrangling-data.html"><i class="fa fa-check"></i><b>4</b> Wrangling data</a>
<ul>
<li class="chapter" data-level="4.1" data-path="wrangling-data.html"><a href="wrangling-data.html#the-goal-tidy-data."><i class="fa fa-check"></i><b>4.1</b> The goal: “tidy” data.</a></li>
<li class="chapter" data-level="4.2" data-path="wrangling-data.html"><a href="wrangling-data.html#the-pipe"><i class="fa fa-check"></i><b>4.2</b> The pipe</a></li>
<li class="chapter" data-level="4.3" data-path="wrangling-data.html"><a href="wrangling-data.html#common-tidying-operations"><i class="fa fa-check"></i><b>4.3</b> Common tidying operations</a></li>
<li class="chapter" data-level="4.4" data-path="wrangling-data.html"><a href="wrangling-data.html#mutate-group-by-and-summarize"><i class="fa fa-check"></i><b>4.4</b> Mutate, group by, and summarize</a></li>
</ul></li>
<li class="chapter" data-level="5" data-path="distribution-calculations.html"><a href="distribution-calculations.html"><i class="fa fa-check"></i><b>5</b> Distribution calculations</a>
<ul>
<li class="chapter" data-level="5.1" data-path="distribution-calculations.html"><a href="distribution-calculations.html#finite-discrete-distribution-calculations"><i class="fa fa-check"></i><b>5.1</b> Finite discrete distribution calculations</a></li>
<li class="chapter" data-level="5.2" data-path="distribution-calculations.html"><a href="distribution-calculations.html#named-distribution-calculations"><i class="fa fa-check"></i><b>5.2</b> Named distribution calculations</a>
<ul>
<li class="chapter" data-level="5.2.1" data-path="distribution-calculations.html"><a href="distribution-calculations.html#discrete-random-variables"><i class="fa fa-check"></i><b>5.2.1</b> Discrete random variables</a></li>
<li class="chapter" data-level="5.2.2" data-path="distribution-calculations.html"><a href="distribution-calculations.html#continuous-random-variables"><i class="fa fa-check"></i><b>5.2.2</b> Continuous random variables</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="6" data-path="inferential-statistics-take-1.html"><a href="inferential-statistics-take-1.html"><i class="fa fa-check"></i><b>6</b> Inferential statistics: Take 1</a>
<ul>
<li class="chapter" data-level="6.1" data-path="inferential-statistics-take-1.html"><a href="inferential-statistics-take-1.html#basics-of-statistical-inference"><i class="fa fa-check"></i><b>6.1</b> Basics of statistical inference</a>
<ul>
<li class="chapter" data-level="6.1.1" data-path="inferential-statistics-take-1.html"><a href="inferential-statistics-take-1.html#sampling-distributions"><i class="fa fa-check"></i><b>6.1.1</b> Sampling distributions</a></li>
<li class="chapter" data-level="6.1.2" data-path="inferential-statistics-take-1.html"><a href="inferential-statistics-take-1.html#confidence-intervals"><i class="fa fa-check"></i><b>6.1.2</b> Confidence intervals</a></li>
<li class="chapter" data-level="6.1.3" data-path="inferential-statistics-take-1.html"><a href="inferential-statistics-take-1.html#hypothesis-tests"><i class="fa fa-check"></i><b>6.1.3</b> Hypothesis tests</a></li>
</ul></li>
<li class="chapter" data-level="6.2" data-path="inferential-statistics-take-1.html"><a href="inferential-statistics-take-1.html#analyzing-categorical-variables"><i class="fa fa-check"></i><b>6.2</b> Analyzing categorical variables</a>
<ul>
<li class="chapter" data-level="6.2.1" data-path="inferential-statistics-take-1.html"><a href="inferential-statistics-take-1.html#single-sample-proportion"><i class="fa fa-check"></i><b>6.2.1</b> Single sample proportion</a></li>
<li class="chapter" data-level="6.2.2" data-path="inferential-statistics-take-1.html"><a href="inferential-statistics-take-1.html#two-sample-proportion"><i class="fa fa-check"></i><b>6.2.2</b> Two sample proportion</a></li>
<li class="chapter" data-level="6.2.3" data-path="inferential-statistics-take-1.html"><a href="inferential-statistics-take-1.html#chi-squared-tests"><i class="fa fa-check"></i><b>6.2.3</b> Chi-squared tests</a></li>
</ul></li>
<li class="chapter" data-level="6.3" data-path="inferential-statistics-take-1.html"><a href="inferential-statistics-take-1.html#analyzing-numerical-variables"><i class="fa fa-check"></i><b>6.3</b> Analyzing numerical variables</a>
<ul>
<li class="chapter" data-level="6.3.1" data-path="inferential-statistics-take-1.html"><a href="inferential-statistics-take-1.html#single-sample-mean"><i class="fa fa-check"></i><b>6.3.1</b> Single sample mean</a></li>
<li class="chapter" data-level="6.3.2" data-path="inferential-statistics-take-1.html"><a href="inferential-statistics-take-1.html#two-sample-mean"><i class="fa fa-check"></i><b>6.3.2</b> Two sample mean</a></li>
<li class="chapter" data-level="6.3.3" data-path="inferential-statistics-take-1.html"><a href="inferential-statistics-take-1.html#paired-data"><i class="fa fa-check"></i><b>6.3.3</b> Paired data</a></li>
<li class="chapter" data-level="6.3.4" data-path="inferential-statistics-take-1.html"><a href="inferential-statistics-take-1.html#analysis-of-variance-anova"><i class="fa fa-check"></i><b>6.3.4</b> Analysis of variance (ANOVA)</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="7" data-path="inferential-statistics-take-2.html"><a href="inferential-statistics-take-2.html"><i class="fa fa-check"></i><b>7</b> Inferential statistics, take 2</a>
<ul>
<li class="chapter" data-level="7.1" data-path="inferential-statistics-take-2.html"><a href="inferential-statistics-take-2.html#analyzing-categorical-variables-1"><i class="fa fa-check"></i><b>7.1</b> Analyzing categorical variables</a>
<ul>
<li class="chapter" data-level="7.1.1" data-path="inferential-statistics-take-2.html"><a href="inferential-statistics-take-2.html#single-sample-proportions"><i class="fa fa-check"></i><b>7.1.1</b> Single sample proportions</a></li>
<li class="chapter" data-level="7.1.2" data-path="inferential-statistics-take-2.html"><a href="inferential-statistics-take-2.html#two-sample-proportions"><i class="fa fa-check"></i><b>7.1.2</b> Two sample proportions</a></li>
<li class="chapter" data-level="7.1.3" data-path="inferential-statistics-take-2.html"><a href="inferential-statistics-take-2.html#chi-squared-goodness-of-fit-test"><i class="fa fa-check"></i><b>7.1.3</b> Chi-squared goodness of fit test</a></li>
<li class="chapter" data-level="7.1.4" data-path="inferential-statistics-take-2.html"><a href="inferential-statistics-take-2.html#chi-squared-test-of-independence-1"><i class="fa fa-check"></i><b>7.1.4</b> Chi-squared test of independence</a></li>
</ul></li>
<li class="chapter" data-level="7.2" data-path="inferential-statistics-take-2.html"><a href="inferential-statistics-take-2.html#analyzing-numerical-variables-1"><i class="fa fa-check"></i><b>7.2</b> Analyzing numerical variables</a>
<ul>
<li class="chapter" data-level="7.2.1" data-path="inferential-statistics-take-2.html"><a href="inferential-statistics-take-2.html#single-sample-mean-1"><i class="fa fa-check"></i><b>7.2.1</b> Single sample mean</a></li>
<li class="chapter" data-level="7.2.2" data-path="inferential-statistics-take-2.html"><a href="inferential-statistics-take-2.html#two-sample-mean-comparison"><i class="fa fa-check"></i><b>7.2.2</b> Two sample mean comparison</a></li>
<li class="chapter" data-level="7.2.3" data-path="inferential-statistics-take-2.html"><a href="inferential-statistics-take-2.html#paired-data-1"><i class="fa fa-check"></i><b>7.2.3</b> Paired data</a></li>
<li class="chapter" data-level="7.2.4" data-path="inferential-statistics-take-2.html"><a href="inferential-statistics-take-2.html#analysis-of-variance-anova-1"><i class="fa fa-check"></i><b>7.2.4</b> Analysis of variance (ANOVA)</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="8" data-path="modeling-relationships.html"><a href="modeling-relationships.html"><i class="fa fa-check"></i><b>8</b> Modeling relationships</a>
<ul>
<li class="chapter" data-level="8.1" data-path="modeling-relationships.html"><a href="modeling-relationships.html#simple-linear-regression"><i class="fa fa-check"></i><b>8.1</b> Simple linear regression</a>
<ul>
<li class="chapter" data-level="8.1.1" data-path="modeling-relationships.html"><a href="modeling-relationships.html#the-basics"><i class="fa fa-check"></i><b>8.1.1</b> The basics</a></li>
<li class="chapter" data-level="8.1.2" data-path="modeling-relationships.html"><a href="modeling-relationships.html#model-fit"><i class="fa fa-check"></i><b>8.1.2</b> Model fit</a></li>
<li class="chapter" data-level="8.1.3" data-path="modeling-relationships.html"><a href="modeling-relationships.html#hypothesis-testing-5"><i class="fa fa-check"></i><b>8.1.3</b> Hypothesis testing</a></li>
<li class="chapter" data-level="8.1.4" data-path="modeling-relationships.html"><a href="modeling-relationships.html#prediction"><i class="fa fa-check"></i><b>8.1.4</b> Prediction</a></li>
</ul></li>
<li class="chapter" data-level="8.2" data-path="modeling-relationships.html"><a href="modeling-relationships.html#multiple-linear-regression"><i class="fa fa-check"></i><b>8.2</b> Multiple linear regression</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="references.html"><a href="references.html"><i class="fa fa-check"></i>References</a></li>
<li class="divider"></li>
<li><a href="https://github.com/rstudio/bookdown" target="blank">Published with bookdown</a></li>

</ul>

      </nav>
    </div>

    <div class="book-body">
      <div class="body-inner">
        <div class="book-header" role="navigation">
          <h1>
            <i class="fa fa-circle-o-notch fa-spin"></i><a href="./">R and RStudio for STAT216</a>
          </h1>
        </div>

        <div class="page-wrapper" tabindex="-1" role="main">
          <div class="page-inner">

            <section class="normal" id="section-">
<div id="inferential-statistics-take-2" class="section level1 hasAnchor" number="7">
<h1><span class="header-section-number">Chapter 7</span> Inferential statistics, take 2<a href="inferential-statistics-take-2.html#inferential-statistics-take-2" class="anchor-section" aria-label="Anchor link to header"></a></h1>
<p>This chapter will show you how to calculate confidence intervals and perform hypothesis tests using R’s in-built hypothesis testing functions. We will quickly go over the same examples from the previous sections using R’s functions to recover the values we calculated earlier.</p>
<div id="analyzing-categorical-variables-1" class="section level2 hasAnchor" number="7.1">
<h2><span class="header-section-number">7.1</span> Analyzing categorical variables<a href="inferential-statistics-take-2.html#analyzing-categorical-variables-1" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>We will learn how to use two workhorse functions in this section: <code>prop.test(...)</code> and <code>chisq.test(...)</code>. The former will be used for making inferences for single and two sample proportions, while the latter will be used for chi squared goodness of fit tests and tests of independence.</p>
<p><strong>Remember</strong> You can always run <code>?prop.test</code> or <code>?chisq.test</code> in the console to view <code>R</code>’s help documentation for these functions.</p>
<div id="single-sample-proportions" class="section level3 hasAnchor" number="7.1.1">
<h3><span class="header-section-number">7.1.1</span> Single sample proportions<a href="inferential-statistics-take-2.html#single-sample-proportions" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>The main function we will use in this section is <code>prop.test(...)</code>; it both calculates confidence intervals <em>and</em> performs hypothesis tests all in one fell swoop! The important things for us, then, are understanding what inputs we need and understanding the outputs. For single-sample proportion inferences, the function <code>prop.test</code> requires the following inputs:</p>
<div class="sourceCode" id="cb562"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb562-1"><a href="inferential-statistics-take-2.html#cb562-1" tabindex="-1"></a><span class="fu">prop.test</span>(</span>
<span id="cb562-2"><a href="inferential-statistics-take-2.html#cb562-2" tabindex="-1"></a>  <span class="at">x =</span> <span class="co"># The number of successes</span></span>
<span id="cb562-3"><a href="inferential-statistics-take-2.html#cb562-3" tabindex="-1"></a>  , <span class="at">n =</span> <span class="co"># the sample size</span></span>
<span id="cb562-4"><a href="inferential-statistics-take-2.html#cb562-4" tabindex="-1"></a>  , <span class="at">p =</span> <span class="co"># the null proportion of your hypothesis test, the default value is NULL</span></span>
<span id="cb562-5"><a href="inferential-statistics-take-2.html#cb562-5" tabindex="-1"></a>  , <span class="at">alternative =</span> <span class="co"># the type of hypothesis test to run corresponding to your alternative hypothesis; one of &quot;two.sided&quot;, &quot;less&quot;, or &quot;greater&quot;</span></span>
<span id="cb562-6"><a href="inferential-statistics-take-2.html#cb562-6" tabindex="-1"></a>  , <span class="at">conf.level =</span> <span class="co"># your confidence level as a decimal</span></span>
<span id="cb562-7"><a href="inferential-statistics-take-2.html#cb562-7" tabindex="-1"></a>  , <span class="at">correct =</span> <span class="cn">FALSE</span> <span class="co"># This turns OFF the Yates&#39; continuity correction so that calculations are made like we&#39;ve learned in class.</span></span>
<span id="cb562-8"><a href="inferential-statistics-take-2.html#cb562-8" tabindex="-1"></a>)</span></code></pre></div>
<p>The function will output the results of our desired hypothesis test and a corresponding confidence interval.</p>
<p><strong>Note:</strong> The confidence interval intervals that <code>R</code> calculates are ever-so-slightly different from those that we calculate by hand in two important ways:</p>
<ul>
<li><p>Setting the option <code>correct = FALSE</code> gets us closer to our by-hand techniques, but <code>R</code> still uses a slightly different method under the hood. See <a href="https://stats.stackexchange.com/questions/183225/confidence-interval-from-rs-prop-test-differs-from-hand-calculation-and-resul">this CrossValidated Stack Exchange post</a> for more information.</p></li>
<li><p>If your alternative hypothesis is one-sided and you select the option <code>alternative = "less"</code> or <code>alternative = "greater"</code>, then <code>R</code> will report a one-sided confidence interval that we do not discuss in this class.</p></li>
</ul>
<p>To understand the output of <code>prop.test(...)</code> and witness the discrepancies mentioned above, let’s return to the 3 basic examples we started with in the previous chapter. Recall that we have a hypothetical example with</p>
<ul>
<li><p><span class="math inline">\(n = 200\)</span></p></li>
<li><p>Our sample has 110 successes, ie <span class="math inline">\(\hat{p} = .55\)</span></p></li>
<li><p>we are comparing our sample data to the null hypothesis <span class="math inline">\(H_0: p = .5\)</span></p></li>
</ul>
<ol style="list-style-type: decimal">
<li><strong>Two-sided hypothesis test:</strong> In this case our hypothesis test is</li>
</ol>
<p><span class="math display">\[\begin{array}{cc}
H_0: p = .5 \\
H_a: p \neq .5
\end{array}
    \]</span></p>
<p>It is quite easy to perform this hypothesis test with the function <code>prop.test(...)</code>, we simply run the following code.</p>
<div class="sourceCode" id="cb563"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb563-1"><a href="inferential-statistics-take-2.html#cb563-1" tabindex="-1"></a>result <span class="ot">&lt;-</span> <span class="fu">prop.test</span>(</span>
<span id="cb563-2"><a href="inferential-statistics-take-2.html#cb563-2" tabindex="-1"></a>  <span class="at">x =</span> <span class="dv">110</span> <span class="co"># the NUMBER of successes</span></span>
<span id="cb563-3"><a href="inferential-statistics-take-2.html#cb563-3" tabindex="-1"></a>  , <span class="at">n =</span> <span class="dv">200</span> <span class="co"># sample size</span></span>
<span id="cb563-4"><a href="inferential-statistics-take-2.html#cb563-4" tabindex="-1"></a>  , <span class="at">p =</span> .<span class="dv">5</span> <span class="co"># the null proportion</span></span>
<span id="cb563-5"><a href="inferential-statistics-take-2.html#cb563-5" tabindex="-1"></a>  , <span class="at">alternative =</span> <span class="st">&quot;two.sided&quot;</span> <span class="co"># since we&#39;re doing a two-sided hypothesis test</span></span>
<span id="cb563-6"><a href="inferential-statistics-take-2.html#cb563-6" tabindex="-1"></a>  , <span class="at">conf.level =</span> .<span class="dv">95</span></span>
<span id="cb563-7"><a href="inferential-statistics-take-2.html#cb563-7" tabindex="-1"></a>  , <span class="at">correct =</span> <span class="cn">FALSE</span></span>
<span id="cb563-8"><a href="inferential-statistics-take-2.html#cb563-8" tabindex="-1"></a>)</span>
<span id="cb563-9"><a href="inferential-statistics-take-2.html#cb563-9" tabindex="-1"></a>result</span></code></pre></div>
<pre><code>## 
##  1-sample proportions test without continuity correction
## 
## data:  110 out of 200, null probability 0.5
## X-squared = 2, df = 1, p-value = 0.1573
## alternative hypothesis: true p is not equal to 0.5
## 95 percent confidence interval:
##  0.4807562 0.6173593
## sample estimates:
##    p 
## 0.55</code></pre>
<p>Notice that the code stores the output of the hypothesis test as the variable <code>result</code>, then prints a summary of the test. Take a few moments to read through the results and notice that it gives us all of the information we want! In particular,</p>
<ul>
<li><p>the “sample estimate” <code>p</code> is the sample proportion <span class="math inline">\(\hat{p}\)</span>;</p></li>
<li><p>the <span class="math inline">\(p\)</span>-value is about 0.1573;</p></li>
<li><p>the associated 95% confidence interval is <span class="math inline">\((0.4807, 0.6173)\)</span>;</p></li>
</ul>
<p>Let’s compare this with the results we’d obtain making the same calculations “by hand. First we’ll calculate a <span class="math inline">\(p\)</span>-value and compare it to that calculated by <code>prop.test</code> above.</p>
<div class="sourceCode" id="cb565"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb565-1"><a href="inferential-statistics-take-2.html#cb565-1" tabindex="-1"></a>n <span class="ot">&lt;-</span> <span class="dv">200</span></span>
<span id="cb565-2"><a href="inferential-statistics-take-2.html#cb565-2" tabindex="-1"></a>pHat <span class="ot">&lt;-</span> <span class="dv">110</span><span class="sc">/</span><span class="dv">200</span></span>
<span id="cb565-3"><a href="inferential-statistics-take-2.html#cb565-3" tabindex="-1"></a>null.SE <span class="ot">&lt;-</span> <span class="fu">sqrt</span>(.<span class="dv">5</span><span class="sc">*</span>.<span class="dv">5</span><span class="sc">/</span><span class="dv">200</span>)</span>
<span id="cb565-4"><a href="inferential-statistics-take-2.html#cb565-4" tabindex="-1"></a>p.value.hand <span class="ot">&lt;-</span> <span class="dv">2</span><span class="sc">*</span><span class="fu">pnorm</span>(pHat, <span class="at">mean =</span> .<span class="dv">5</span>, <span class="at">sd =</span> null.SE, <span class="at">lower.tail =</span> <span class="cn">FALSE</span>)</span>
<span id="cb565-5"><a href="inferential-statistics-take-2.html#cb565-5" tabindex="-1"></a></span>
<span id="cb565-6"><a href="inferential-statistics-take-2.html#cb565-6" tabindex="-1"></a><span class="fu">c</span>(p.value.hand, result<span class="sc">$</span>p.value)</span></code></pre></div>
<pre><code>## [1] 0.1572992 0.1572992</code></pre>
<p>They’re the same, just as we would hope. Now let’s calculate a 95% confidence interval “by hand” and compare the results to that calculated by <code>prop.test</code> above.</p>
<div class="sourceCode" id="cb567"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb567-1"><a href="inferential-statistics-take-2.html#cb567-1" tabindex="-1"></a>conf.int.hand <span class="ot">&lt;-</span> pHat <span class="sc">+</span> <span class="fu">c</span>(<span class="sc">-</span><span class="dv">1</span>,<span class="dv">1</span>)<span class="sc">*</span><span class="fl">1.96</span><span class="sc">*</span>null.SE</span>
<span id="cb567-2"><a href="inferential-statistics-take-2.html#cb567-2" tabindex="-1"></a><span class="co"># our result</span></span>
<span id="cb567-3"><a href="inferential-statistics-take-2.html#cb567-3" tabindex="-1"></a>conf.int.hand</span></code></pre></div>
<pre><code>## [1] 0.4807035 0.6192965</code></pre>
<div class="sourceCode" id="cb569"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb569-1"><a href="inferential-statistics-take-2.html#cb569-1" tabindex="-1"></a><span class="co">#from prop.test</span></span>
<span id="cb569-2"><a href="inferential-statistics-take-2.html#cb569-2" tabindex="-1"></a>result<span class="sc">$</span>conf.in</span></code></pre></div>
<pre><code>## [1] 0.4807562 0.6173593
## attr(,&quot;conf.level&quot;)
## [1] 0.95</code></pre>
<p>Notice that the bounds of our “by hand” calculation are ever so slightly different from the bounds calculated by <code>prop.test</code> - this is because R calculates these confidence intervals with slightly different and more sophisticated techniques than we cover in this class. Fret not, however, as the outputs in most cases are similar enough. One interesting thing to observer is that the confidence interval from <code>prop.test</code> is <em>not</em> symmetric about the sample proportion <span class="math inline">\(\hat{p}\)</span>!</p>
<p>In our remaining examples, we will move a little more quickly.</p>
<ol start="2" style="list-style-type: decimal">
<li><strong>One-sided lower hypothesis test:</strong> In this case our hypothesis test is</li>
</ol>
<p><span class="math display">\[\begin{array}{cc}
H_0: p = .5 \\
H_a: p &lt; .5
\end{array}
    \]</span></p>
<p>This hypothesis test is quite easy to evaluate as well will <code>prop.test</code>. See the code below:</p>
<div class="sourceCode" id="cb571"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb571-1"><a href="inferential-statistics-take-2.html#cb571-1" tabindex="-1"></a>result <span class="ot">&lt;-</span> <span class="fu">prop.test</span>(</span>
<span id="cb571-2"><a href="inferential-statistics-take-2.html#cb571-2" tabindex="-1"></a>  <span class="at">x =</span> <span class="dv">110</span> <span class="co"># the NUMBER of successes</span></span>
<span id="cb571-3"><a href="inferential-statistics-take-2.html#cb571-3" tabindex="-1"></a>  , <span class="at">n =</span> <span class="dv">200</span> <span class="co"># sample size</span></span>
<span id="cb571-4"><a href="inferential-statistics-take-2.html#cb571-4" tabindex="-1"></a>  , <span class="at">p =</span> .<span class="dv">5</span> <span class="co"># the null proportion</span></span>
<span id="cb571-5"><a href="inferential-statistics-take-2.html#cb571-5" tabindex="-1"></a>  , <span class="at">alternative =</span> <span class="st">&quot;less&quot;</span> <span class="co"># ONLY CHANGE FROM Above</span></span>
<span id="cb571-6"><a href="inferential-statistics-take-2.html#cb571-6" tabindex="-1"></a>  , <span class="at">conf.level =</span> .<span class="dv">95</span></span>
<span id="cb571-7"><a href="inferential-statistics-take-2.html#cb571-7" tabindex="-1"></a>  , <span class="at">correct =</span> <span class="cn">FALSE</span></span>
<span id="cb571-8"><a href="inferential-statistics-take-2.html#cb571-8" tabindex="-1"></a>)</span>
<span id="cb571-9"><a href="inferential-statistics-take-2.html#cb571-9" tabindex="-1"></a>result</span></code></pre></div>
<pre><code>## 
##  1-sample proportions test without continuity correction
## 
## data:  110 out of 200, null probability 0.5
## X-squared = 2, df = 1, p-value = 0.9214
## alternative hypothesis: true p is less than 0.5
## 95 percent confidence interval:
##  0.0000000 0.6068119
## sample estimates:
##    p 
## 0.55</code></pre>
<p>Most of the output is exactly as we’d expect it to be. The <span class="math inline">\(p\)</span>-value of this test is the complement of half of the <span class="math inline">\(p\)</span>-value from the two-sided test (think about the corresponding tail areas shaded under a normal distribution) and the point estimate is the same.</p>
<p><strong>Caution:</strong> The main change is the output of the confidence interval. Because this is a one-sided tests, R reports a one-sided confidence interval that we do not cover in this class. Suppose <span class="math inline">\(\alpha\)</span> is the significance level as decimal with corresponding <span class="math inline">\(z\)</span>-critical value <span class="math inline">\(z_\alpha\)</span>. Then a one-sided lower confidence interval is approximately</p>
<p><span class="math display">\[ \left( 0, \hat{p} + z_\alpha * SE\right) \]</span></p>
<p>For our example, we can calculate this by hand for a 95% confidence interval, the corresponding significance level is .05, so <span class="math inline">\(\alpha = .05\)</span>.</p>
<div class="sourceCode" id="cb573"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb573-1"><a href="inferential-statistics-take-2.html#cb573-1" tabindex="-1"></a>z.crit <span class="ot">&lt;-</span> <span class="fu">qnorm</span>(.<span class="dv">05</span>, <span class="at">lower.tail =</span> F)</span>
<span id="cb573-2"><a href="inferential-statistics-take-2.html#cb573-2" tabindex="-1"></a>pHat <span class="sc">+</span> z.crit<span class="sc">*</span>null.SE</span></code></pre></div>
<pre><code>## [1] 0.6081544</code></pre>
<p>This is very close to, but not exactly, the upper bound of the confidence interval given by R’s <code>prop.test</code> function. For our purposes they are close enough. That said, if you are looking for a confidence interval as we calculate them in class, set the <code>alternative</code> option to <code>"two.sided"</code>.</p>
<ol start="2" style="list-style-type: decimal">
<li><strong>One-sided upper hypothesis test:</strong> In this case our hypothesis test is</li>
</ol>
<p><span class="math display">\[\begin{array}{cc}
H_0: p = .5 \\
H_a: p &gt; .5
\end{array}
    \]</span></p>
<p>This hypothesis test is quite easy to evaluate as well will <code>prop.test</code>. See the code below:</p>
<div class="sourceCode" id="cb575"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb575-1"><a href="inferential-statistics-take-2.html#cb575-1" tabindex="-1"></a>result <span class="ot">&lt;-</span> <span class="fu">prop.test</span>(</span>
<span id="cb575-2"><a href="inferential-statistics-take-2.html#cb575-2" tabindex="-1"></a>  <span class="at">x =</span> <span class="dv">110</span> <span class="co"># the NUMBER of successes</span></span>
<span id="cb575-3"><a href="inferential-statistics-take-2.html#cb575-3" tabindex="-1"></a>  , <span class="at">n =</span> <span class="dv">200</span> <span class="co"># sample size</span></span>
<span id="cb575-4"><a href="inferential-statistics-take-2.html#cb575-4" tabindex="-1"></a>  , <span class="at">p =</span> .<span class="dv">5</span> <span class="co"># the null proportion</span></span>
<span id="cb575-5"><a href="inferential-statistics-take-2.html#cb575-5" tabindex="-1"></a>  , <span class="at">alternative =</span> <span class="st">&quot;greater&quot;</span> <span class="co"># ONLY CHANGE FROM Above</span></span>
<span id="cb575-6"><a href="inferential-statistics-take-2.html#cb575-6" tabindex="-1"></a>  , <span class="at">conf.level =</span> .<span class="dv">95</span></span>
<span id="cb575-7"><a href="inferential-statistics-take-2.html#cb575-7" tabindex="-1"></a>  , <span class="at">correct =</span> <span class="cn">FALSE</span></span>
<span id="cb575-8"><a href="inferential-statistics-take-2.html#cb575-8" tabindex="-1"></a>)</span>
<span id="cb575-9"><a href="inferential-statistics-take-2.html#cb575-9" tabindex="-1"></a>result</span></code></pre></div>
<pre><code>## 
##  1-sample proportions test without continuity correction
## 
## data:  110 out of 200, null probability 0.5
## X-squared = 2, df = 1, p-value = 0.07865
## alternative hypothesis: true p is greater than 0.5
## 95 percent confidence interval:
##  0.4918534 1.0000000
## sample estimates:
##    p 
## 0.55</code></pre>
<p>The result of this test is very similar to the output from the one-sided lower example and all of the same comments apply. Again, the main change is the reported confidence interval.</p>
<p><strong>Caution:</strong> As in the case of a one-sided lower test, R reports a one-sided confidence interval, which deviates from what we learn in this class! Suppose <span class="math inline">\(\alpha\)</span> is the significance level as decimal with corresponding <span class="math inline">\(z\)</span>-critical value <span class="math inline">\(z_\alpha\)</span>. Then a one-sided lower confidence interval is approximately</p>
<p><span class="math display">\[ \left( \hat{p} - z_\alpha * SE, 1 \right)  \]</span></p>
<p>For our example, we can calculate this by hand for a 95% confidence interval, the corresponding significance level is .05, so <span class="math inline">\(\alpha = .05\)</span>. The lower-bound for the one-sided confidence interval is</p>
<div class="sourceCode" id="cb577"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb577-1"><a href="inferential-statistics-take-2.html#cb577-1" tabindex="-1"></a>z.crit <span class="ot">&lt;-</span> <span class="fu">qnorm</span>(.<span class="dv">05</span>, <span class="at">lower.tail =</span> F)</span>
<span id="cb577-2"><a href="inferential-statistics-take-2.html#cb577-2" tabindex="-1"></a>pHat <span class="sc">-</span> z.crit<span class="sc">*</span>null.SE</span></code></pre></div>
<pre><code>## [1] 0.4918456</code></pre>
<p>This is very close to, but not exactly, the lower bound of the confidence interval given by R’s <code>prop.test</code> function.</p>
<p>As a reminder, if you are looking for a confidence interval as we calculate them in class, set the <code>alternative</code> option to <code>"two.sided"</code>.</p>
<div id="real-life-single-sample-proportion-test." class="section level4 hasAnchor" number="7.1.1.1">
<h4><span class="header-section-number">7.1.1.1</span> “Real Life” Single sample proportion test.<a href="inferential-statistics-take-2.html#real-life-single-sample-proportion-test." class="anchor-section" aria-label="Anchor link to header"></a></h4>
<p>We close this section with an example of a single sample proportion test where we start with real-world data. As in the previous chapter we’ll use the <code>gss2010</code> data set from the <code>openintro</code> package. Here are the first six rows of this data set.</p>
<div class="sourceCode" id="cb579"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb579-1"><a href="inferential-statistics-take-2.html#cb579-1" tabindex="-1"></a><span class="fu">head</span>(gss2010)</span></code></pre></div>
<pre><code>## # A tibble: 6 × 5
##   hrsrelax mntlhlth  hrs1 degree         grass    
##      &lt;int&gt;    &lt;int&gt; &lt;int&gt; &lt;fct&gt;          &lt;fct&gt;    
## 1        2        3    55 BACHELOR       &lt;NA&gt;     
## 2        4        6    45 BACHELOR       LEGAL    
## 3       NA       NA    NA LT HIGH SCHOOL &lt;NA&gt;     
## 4       NA       NA    NA LT HIGH SCHOOL NOT LEGAL
## 5       NA       NA    NA LT HIGH SCHOOL NOT LEGAL
## 6       NA       NA    NA LT HIGH SCHOOL LEGAL</code></pre>
<p>As of writing, we note that marijuana is legal in many states, so we will assume that a majority of American’s in 2024 believe that the drug should be legalized. We want to use the <code>gss2010</code> data to try to see if the national opinion has changed over the past 14 years. In other words, did a minority of Americans think marijuana should be legalized in 2010?</p>
<p>If <span class="math inline">\(p\)</span> denotes the proportion of Americans who think marijuana should be legalized, the hypothesis test we should use to answer this question is</p>
<p><span class="math display">\[\begin{array}{cc}
H_0: p = .5 \quad (\text{or} \quad p \geq .5) \\
H_a: p &lt; .5
\end{array}
    \]</span></p>
<p>We should look at the <code>grass</code> column of the data set which records respondents’ answers to the question “Do you think the use of marijuana should be made legal, or not?” Some of the entries in this column are <code>NA</code>, so we should drop these values from our data set. <strong>Note:</strong> before dropping these values, it might be good to check to see if there’s a correlation between the respondents who did not reply and their educational level because degree is the only complete column in this data set and we need to be careful about maintaining independence among observations. One could check this with a chi-squared test of independence, but we will eyeball it for now.</p>
<div class="sourceCode" id="cb581"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb581-1"><a href="inferential-statistics-take-2.html#cb581-1" tabindex="-1"></a>gss2010 <span class="sc">%&gt;%</span></span>
<span id="cb581-2"><a href="inferential-statistics-take-2.html#cb581-2" tabindex="-1"></a>  <span class="co"># add a binary column for replying to the grass question</span></span>
<span id="cb581-3"><a href="inferential-statistics-take-2.html#cb581-3" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">grassReply =</span> <span class="fu">if_else</span>(<span class="fu">is.na</span>(grass),  <span class="st">&#39;No&#39;</span>, <span class="st">&#39;Yes&#39;</span>)) <span class="sc">%&gt;%</span></span>
<span id="cb581-4"><a href="inferential-statistics-take-2.html#cb581-4" tabindex="-1"></a>  <span class="co"># create a two-way table for degree and grassReply</span></span>
<span id="cb581-5"><a href="inferential-statistics-take-2.html#cb581-5" tabindex="-1"></a>  <span class="fu">xtabs</span>(<span class="sc">~</span>degree <span class="sc">+</span> grassReply, <span class="at">data =</span> .) <span class="sc">%&gt;%</span></span>
<span id="cb581-6"><a href="inferential-statistics-take-2.html#cb581-6" tabindex="-1"></a>  <span class="co"># create a proportion table where we divide by the column totals</span></span>
<span id="cb581-7"><a href="inferential-statistics-take-2.html#cb581-7" tabindex="-1"></a>  <span class="fu">prop.table</span>(., <span class="at">margin =</span> <span class="dv">2</span>)</span></code></pre></div>
<pre><code>##                 grassReply
## degree                   No        Yes
##   BACHELOR       0.18343949 0.18347895
##   GRADUATE       0.10445860 0.10802224
##   HIGH SCHOOL    0.49681529 0.48530580
##   JUNIOR COLLEGE 0.07515924 0.06830818
##   LT HIGH SCHOOL 0.14012739 0.15488483</code></pre>
<p>The proportion table above shows that the distribution of educational attainment is just about the same between those that did and did not reply to the question about marijuana legalization. Thus, we can safely drop the <code>NA</code> values from the grass column and proceed with our hypothesis test. To use <code>prop.test</code> we need the sample size and the number of people who responded <code>LEGAL</code> to the grass question.</p>
<div class="sourceCode" id="cb583"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb583-1"><a href="inferential-statistics-take-2.html#cb583-1" tabindex="-1"></a>gss2010 <span class="sc">%&gt;%</span> </span>
<span id="cb583-2"><a href="inferential-statistics-take-2.html#cb583-2" tabindex="-1"></a>  <span class="co">#select all rows where grass is not NA</span></span>
<span id="cb583-3"><a href="inferential-statistics-take-2.html#cb583-3" tabindex="-1"></a>  <span class="fu">filter</span>(<span class="sc">!</span><span class="fu">is.na</span>(grass)) <span class="sc">%&gt;%</span></span>
<span id="cb583-4"><a href="inferential-statistics-take-2.html#cb583-4" tabindex="-1"></a>  <span class="co"># get sample size and number of respondents answering legal and not legal</span></span>
<span id="cb583-5"><a href="inferential-statistics-take-2.html#cb583-5" tabindex="-1"></a>  <span class="fu">summarize</span>(</span>
<span id="cb583-6"><a href="inferential-statistics-take-2.html#cb583-6" tabindex="-1"></a>    <span class="at">n =</span> <span class="fu">n</span>()</span>
<span id="cb583-7"><a href="inferential-statistics-take-2.html#cb583-7" tabindex="-1"></a>    , <span class="at">notLegal =</span> <span class="fu">sum</span>(grass <span class="sc">==</span> <span class="st">&#39;NOT LEGAL&#39;</span>)</span>
<span id="cb583-8"><a href="inferential-statistics-take-2.html#cb583-8" tabindex="-1"></a>    , <span class="at">legal =</span> <span class="fu">sum</span>(grass <span class="sc">==</span> <span class="st">&#39;LEGAL&#39;</span>)</span>
<span id="cb583-9"><a href="inferential-statistics-take-2.html#cb583-9" tabindex="-1"></a>  )</span></code></pre></div>
<pre><code>## # A tibble: 1 × 3
##       n notLegal legal
##   &lt;int&gt;    &lt;int&gt; &lt;int&gt;
## 1  1259      656   603</code></pre>
<p>We can finally proceed with our hypothesis test. Let’s use a significance level of <span class="math inline">\(\alpha = .05\)</span></p>
<div class="sourceCode" id="cb585"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb585-1"><a href="inferential-statistics-take-2.html#cb585-1" tabindex="-1"></a>testResults <span class="ot">&lt;-</span> <span class="fu">prop.test</span>(</span>
<span id="cb585-2"><a href="inferential-statistics-take-2.html#cb585-2" tabindex="-1"></a>  <span class="at">x =</span> <span class="dv">603</span></span>
<span id="cb585-3"><a href="inferential-statistics-take-2.html#cb585-3" tabindex="-1"></a>  , <span class="at">n =</span> <span class="dv">1259</span></span>
<span id="cb585-4"><a href="inferential-statistics-take-2.html#cb585-4" tabindex="-1"></a>  , <span class="at">p =</span> .<span class="dv">5</span></span>
<span id="cb585-5"><a href="inferential-statistics-take-2.html#cb585-5" tabindex="-1"></a>  , <span class="at">alternative =</span> <span class="st">&#39;less&#39;</span></span>
<span id="cb585-6"><a href="inferential-statistics-take-2.html#cb585-6" tabindex="-1"></a>  , <span class="at">conf.level =</span> .<span class="dv">95</span></span>
<span id="cb585-7"><a href="inferential-statistics-take-2.html#cb585-7" tabindex="-1"></a>  , <span class="at">correct =</span> F</span>
<span id="cb585-8"><a href="inferential-statistics-take-2.html#cb585-8" tabindex="-1"></a>)</span>
<span id="cb585-9"><a href="inferential-statistics-take-2.html#cb585-9" tabindex="-1"></a>testResults</span></code></pre></div>
<pre><code>## 
##  1-sample proportions test without continuity correction
## 
## data:  603 out of 1259, null probability 0.5
## X-squared = 2.2311, df = 1, p-value = 0.06763
## alternative hypothesis: true p is less than 0.5
## 95 percent confidence interval:
##  0.0000000 0.5021298
## sample estimates:
##         p 
## 0.4789515</code></pre>
<p>About 48% of the respondents in our sample believed that marijuana should be legalized. However, our p-value of 0.068 is greater than our significance level, so we fail to reject the null. In other words, we have no evidence that a minority of Americans supported marijuana legalization in 2010.</p>
</div>
</div>
<div id="two-sample-proportions" class="section level3 hasAnchor" number="7.1.2">
<h3><span class="header-section-number">7.1.2</span> Two sample proportions<a href="inferential-statistics-take-2.html#two-sample-proportions" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>The main function we will use in this section is again <code>prop.test(...)</code>. In this section we will do one ‘toy’ example and one example using real-world data. The input and use is almost identical to that of performing single sample proportion inferences. The arguments/inputs are as follows.</p>
<div class="sourceCode" id="cb587"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb587-1"><a href="inferential-statistics-take-2.html#cb587-1" tabindex="-1"></a><span class="fu">prop.test</span>(</span>
<span id="cb587-2"><a href="inferential-statistics-take-2.html#cb587-2" tabindex="-1"></a>  <span class="co"># x1 and x2 are the number of successes in sample 1 and 2</span></span>
<span id="cb587-3"><a href="inferential-statistics-take-2.html#cb587-3" tabindex="-1"></a>  <span class="at">x =</span> <span class="fu">c</span>(x1, x2)  </span>
<span id="cb587-4"><a href="inferential-statistics-take-2.html#cb587-4" tabindex="-1"></a>  <span class="co"># n1 and n2 are the sizes of sample 1 and 2</span></span>
<span id="cb587-5"><a href="inferential-statistics-take-2.html#cb587-5" tabindex="-1"></a>  , <span class="at">n =</span> <span class="fu">c</span>(n1,n2)</span>
<span id="cb587-6"><a href="inferential-statistics-take-2.html#cb587-6" tabindex="-1"></a>  <span class="co"># leave p null when testing for a difference in proportion, our most common use</span></span>
<span id="cb587-7"><a href="inferential-statistics-take-2.html#cb587-7" tabindex="-1"></a>  , <span class="at">p =</span> <span class="cn">NULL</span></span>
<span id="cb587-8"><a href="inferential-statistics-take-2.html#cb587-8" tabindex="-1"></a>  , <span class="at">alternative =</span> <span class="co"># the type of hypothesis test to run corresponding to your alternative hypothesis; one of &quot;two.sided&quot;, &quot;less&quot;, or &quot;greater&quot;</span></span>
<span id="cb587-9"><a href="inferential-statistics-take-2.html#cb587-9" tabindex="-1"></a>  , <span class="at">conf.level =</span> <span class="co"># your confidence level as a decimal</span></span>
<span id="cb587-10"><a href="inferential-statistics-take-2.html#cb587-10" tabindex="-1"></a>  , <span class="at">correct =</span> <span class="cn">FALSE</span> <span class="co"># This turns OFF the Yates&#39; continuity correction so that calculations are made like we&#39;ve learned in class.</span></span>
<span id="cb587-11"><a href="inferential-statistics-take-2.html#cb587-11" tabindex="-1"></a>)</span></code></pre></div>
<p>The output of <code>prop.test</code> will look almost identical to when you perform a single sample inference and all of our cautions and commentary from the previous section apply in this section as well. First we’ll do a basic, made up example to see what the output looks like, then do an example with real data to practice interpreting the results.</p>
<p><strong>Basic, made up example</strong>: Suppose you have two samples, one with size <span class="math inline">\(n_1 = 344\)</span> and another with size <span class="math inline">\(n_2 = 432\)</span>. The first sample has 177 successes and the second has 124. You want check for a difference between the proportion of successes in populations 1 and 2. In other words, your hypothesis test is</p>
<p><span class="math display">\[\begin{array}{cc}
H_0: p_1 - p_2 = 0 \\
H_a: p_1 - p_2 \neq 0
\end{array}
    \]</span></p>
<p>The following code uses <code>prop.test</code> to perform this hypothesis test with a significance level of <span class="math inline">\(\alpha = .05\)</span></p>
<div class="sourceCode" id="cb588"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb588-1"><a href="inferential-statistics-take-2.html#cb588-1" tabindex="-1"></a>results <span class="ot">&lt;-</span> <span class="fu">prop.test</span>(</span>
<span id="cb588-2"><a href="inferential-statistics-take-2.html#cb588-2" tabindex="-1"></a>  <span class="at">x =</span> <span class="fu">c</span>(<span class="dv">177</span>, <span class="dv">124</span>)</span>
<span id="cb588-3"><a href="inferential-statistics-take-2.html#cb588-3" tabindex="-1"></a>  , <span class="at">n =</span> <span class="fu">c</span>(<span class="dv">344</span>, <span class="dv">432</span>)</span>
<span id="cb588-4"><a href="inferential-statistics-take-2.html#cb588-4" tabindex="-1"></a>  , <span class="at">alternative =</span> <span class="st">&#39;two.sided&#39;</span></span>
<span id="cb588-5"><a href="inferential-statistics-take-2.html#cb588-5" tabindex="-1"></a>  , <span class="at">conf.level =</span> .<span class="dv">95</span></span>
<span id="cb588-6"><a href="inferential-statistics-take-2.html#cb588-6" tabindex="-1"></a>  , <span class="at">correct =</span> <span class="cn">FALSE</span></span>
<span id="cb588-7"><a href="inferential-statistics-take-2.html#cb588-7" tabindex="-1"></a>)</span>
<span id="cb588-8"><a href="inferential-statistics-take-2.html#cb588-8" tabindex="-1"></a>results</span></code></pre></div>
<pre><code>## 
##  2-sample test for equality of proportions without continuity correction
## 
## data:  c(177, 124) out of c(344, 432)
## X-squared = 41.744, df = 1, p-value = 1.04e-10
## alternative hypothesis: two.sided
## 95 percent confidence interval:
##  0.1596070 0.2953887
## sample estimates:
##    prop 1    prop 2 
## 0.5145349 0.2870370</code></pre>
<p>The printed <code>results</code> above give us all of the information we need. The <span class="math inline">\(p\)</span>-value of our test is <span class="math inline">\(1.0401892\times 10^{-10} &lt; \alpha = .05\)</span>, so the data provide compelling evidence of a difference between the population proportions.</p>
<p>How different are the two proportions you ask? Remember, that’s exactly what the confidence interval for a difference in proportions reports. In this case, it means that <span class="math inline">\(p_1 - p_2\)</span> lies between about 16% and 30% with 95% confidence. In other words, with 95% confidence, the proportion of successes in population 1 is between 16% and 30% higher than the proportion of successes in population 2.</p>
<div id="real-world-example" class="section level4 hasAnchor" number="7.1.2.1">
<h4><span class="header-section-number">7.1.2.1</span> “Real world” Example<a href="inferential-statistics-take-2.html#real-world-example" class="anchor-section" aria-label="Anchor link to header"></a></h4>
<p>In this example we turn again to the <code>gss2010</code> data set from the <code>openintro</code> package and investigate another question about marijuana legalization opinion. After many years around colleges and universities, I hypothesize that, in general, people with college degrees have a different opinion on marijuana legalization than people without college degrees.</p>
<p>Let <span class="math inline">\(p_C\)</span> denote the proportion of Americans with college degrees who think marijuana should be legalized and let <span class="math inline">\(p_H\)</span> be the same proportion for Americans without college degrees. Our hypothesis test is then</p>
<p><span class="math display">\[\begin{array}{cc}
H_0: p_C - p_H = 0 \\
H_a: p_C - p_H \neq 0
\end{array}
    \]</span></p>
<p>We need to classify group the individuals in our sample into college degree recipients and non college degree recipients. The different levels of the <code>degree</code> factor are</p>
<div class="sourceCode" id="cb590"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb590-1"><a href="inferential-statistics-take-2.html#cb590-1" tabindex="-1"></a><span class="fu">sort</span>(<span class="fu">unique</span>(gss2010<span class="sc">$</span>degree))</span></code></pre></div>
<pre><code>## [1] BACHELOR       GRADUATE       HIGH SCHOOL    JUNIOR COLLEGE LT HIGH SCHOOL
## Levels: BACHELOR GRADUATE HIGH SCHOOL JUNIOR COLLEGE LT HIGH SCHOOL</code></pre>
<p>so any individual whose degree level contains the string ‘HIGH SCHOOL’ does <em>not</em> have a college degree. Let’s add a column to our data set, then get the counts we need to perform our test. As in the example in the last section, we will drop the individuals who did not respond to the legalization question. To make the hypothesis test slightly easier to run, we will store the following summary table in memory.</p>
<div class="sourceCode" id="cb592"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb592-1"><a href="inferential-statistics-take-2.html#cb592-1" tabindex="-1"></a>LegalizeIt <span class="ot">&lt;-</span> gss2010 <span class="sc">%&gt;%</span></span>
<span id="cb592-2"><a href="inferential-statistics-take-2.html#cb592-2" tabindex="-1"></a>  <span class="co">#drop rows with NA in grass column</span></span>
<span id="cb592-3"><a href="inferential-statistics-take-2.html#cb592-3" tabindex="-1"></a>  <span class="fu">filter</span>(<span class="sc">!</span><span class="fu">is.na</span>(grass)) <span class="sc">%&gt;%</span></span>
<span id="cb592-4"><a href="inferential-statistics-take-2.html#cb592-4" tabindex="-1"></a>  <span class="co"># TRUE/FALSE binary for college degree</span></span>
<span id="cb592-5"><a href="inferential-statistics-take-2.html#cb592-5" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">collegeDegree =</span> <span class="sc">!</span><span class="fu">str_detect</span>(degree, <span class="st">&#39;HIGH SCHOOL&#39;</span>)) <span class="sc">%&gt;%</span></span>
<span id="cb592-6"><a href="inferential-statistics-take-2.html#cb592-6" tabindex="-1"></a>  <span class="fu">group_by</span>(collegeDegree) <span class="sc">%&gt;%</span></span>
<span id="cb592-7"><a href="inferential-statistics-take-2.html#cb592-7" tabindex="-1"></a>  <span class="fu">summarize</span>(</span>
<span id="cb592-8"><a href="inferential-statistics-take-2.html#cb592-8" tabindex="-1"></a>    <span class="at">n =</span> <span class="fu">n</span>()</span>
<span id="cb592-9"><a href="inferential-statistics-take-2.html#cb592-9" tabindex="-1"></a>    , <span class="at">legal =</span> <span class="fu">sum</span>(grass <span class="sc">==</span> <span class="st">&#39;LEGAL&#39;</span>)</span>
<span id="cb592-10"><a href="inferential-statistics-take-2.html#cb592-10" tabindex="-1"></a>    , <span class="at">notLegal =</span> <span class="fu">sum</span>(grass <span class="sc">==</span> <span class="st">&#39;NOT LEGAL&#39;</span>)</span>
<span id="cb592-11"><a href="inferential-statistics-take-2.html#cb592-11" tabindex="-1"></a>  ) <span class="sc">%&gt;%</span></span>
<span id="cb592-12"><a href="inferential-statistics-take-2.html#cb592-12" tabindex="-1"></a>  <span class="co">#arrange the results so that collegeDegree = TRUE comes first. </span></span>
<span id="cb592-13"><a href="inferential-statistics-take-2.html#cb592-13" tabindex="-1"></a>  <span class="fu">arrange</span>(<span class="fu">desc</span>(collegeDegree))</span>
<span id="cb592-14"><a href="inferential-statistics-take-2.html#cb592-14" tabindex="-1"></a>LegalizeIt</span></code></pre></div>
<pre><code>## # A tibble: 2 × 4
##   collegeDegree     n legal notLegal
##   &lt;lgl&gt;         &lt;int&gt; &lt;int&gt;    &lt;int&gt;
## 1 TRUE            453   234      219
## 2 FALSE           806   369      437</code></pre>
<p>Now we are ready to perform our hypothesis test with <code>prop.test</code> and a significance level of <span class="math inline">\(\alpha = .05\)</span>.</p>
<div class="sourceCode" id="cb594"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb594-1"><a href="inferential-statistics-take-2.html#cb594-1" tabindex="-1"></a>results <span class="ot">&lt;-</span> <span class="fu">prop.test</span>(</span>
<span id="cb594-2"><a href="inferential-statistics-take-2.html#cb594-2" tabindex="-1"></a>  <span class="at">x =</span> LegalizeIt<span class="sc">$</span>legal</span>
<span id="cb594-3"><a href="inferential-statistics-take-2.html#cb594-3" tabindex="-1"></a>  , <span class="at">n =</span> LegalizeIt<span class="sc">$</span>n</span>
<span id="cb594-4"><a href="inferential-statistics-take-2.html#cb594-4" tabindex="-1"></a>  , <span class="at">p =</span> <span class="cn">NULL</span></span>
<span id="cb594-5"><a href="inferential-statistics-take-2.html#cb594-5" tabindex="-1"></a>  , <span class="at">alternative =</span> <span class="st">&#39;two.sided&#39;</span></span>
<span id="cb594-6"><a href="inferential-statistics-take-2.html#cb594-6" tabindex="-1"></a>  , <span class="at">conf.level =</span> .<span class="dv">95</span></span>
<span id="cb594-7"><a href="inferential-statistics-take-2.html#cb594-7" tabindex="-1"></a>  , <span class="at">correct =</span> <span class="cn">FALSE</span></span>
<span id="cb594-8"><a href="inferential-statistics-take-2.html#cb594-8" tabindex="-1"></a>)</span>
<span id="cb594-9"><a href="inferential-statistics-take-2.html#cb594-9" tabindex="-1"></a>results </span></code></pre></div>
<pre><code>## 
##  2-sample test for equality of proportions without continuity correction
## 
## data:  LegalizeIt$legal out of LegalizeIt$n
## X-squared = 4.0096, df = 1, p-value = 0.04524
## alternative hypothesis: two.sided
## 95 percent confidence interval:
##  0.001287983 0.116191845
## sample estimates:
##    prop 1    prop 2 
## 0.5165563 0.4578164</code></pre>
<p>The p-value of our test is 0.045 which just squeezes in under <span class="math inline">\(\alpha = .05\)</span>, so we have statistically significant evidence that there is a difference in opinion on marijuana legalization between those with and without college degrees.</p>
<p>We can use the confidence interval from our results to be a bit more specific. At the 95% confidence level, the proportion of people with college degrees who think marijuana should be legalized is between 0.1% and 11.6% higher than the proportion of people without college degrees.</p>
<p>Remember, this was all calculated using 2010 data, so you may want to redo this investigation with more up-to-date information.</p>
</div>
</div>
<div id="chi-squared-goodness-of-fit-test" class="section level3 hasAnchor" number="7.1.3">
<h3><span class="header-section-number">7.1.3</span> Chi-squared goodness of fit test<a href="inferential-statistics-take-2.html#chi-squared-goodness-of-fit-test" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>A goodness of fit test checks to see if your sample data deviates from some expected distribution. For example, you can use this type of test to investigate whether political affiliation in a county deviates from the state that that county is in or test to see if your dice are actually fair.</p>
<p>To perform a chi-squared goodness of fit test easily in <code>R</code> we will use the function <code>chisq.test(...)</code>. The inputs to this function are as follows:</p>
<div class="sourceCode" id="cb596"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb596-1"><a href="inferential-statistics-take-2.html#cb596-1" tabindex="-1"></a><span class="fu">chisq.test</span>( <span class="at">x =</span> <span class="fu">c</span>(...) <span class="co"># a list of your observed counts</span></span>
<span id="cb596-2"><a href="inferential-statistics-take-2.html#cb596-2" tabindex="-1"></a>            , <span class="at">p =</span> <span class="fu">c</span>(...) <span class="co"># a vector of your expected proportions/probabilities</span></span>
<span id="cb596-3"><a href="inferential-statistics-take-2.html#cb596-3" tabindex="-1"></a>            , <span class="at">correct =</span> F <span class="co"># turn off the continuity correction, like usual</span></span>
<span id="cb596-4"><a href="inferential-statistics-take-2.html#cb596-4" tabindex="-1"></a>            )</span></code></pre></div>
<p>We will look at pet ownership in Seattle as an example of a goodness of fit test. From <a href="www.zipatlas.com">www.zipatlas.com</a>, the 10 most populous zip codes in the Seattle metro area are those in the table below. The column <code>pop</code> gives the zip codes population in 2024. Note: we change zipcode the a character vector to treat them deservedly as categorical variables.</p>
<div class="sourceCode" id="cb597"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb597-1"><a href="inferential-statistics-take-2.html#cb597-1" tabindex="-1"></a>zipDF <span class="ot">&lt;-</span> <span class="fu">tibble</span>(</span>
<span id="cb597-2"><a href="inferential-statistics-take-2.html#cb597-2" tabindex="-1"></a>  <span class="at">zip =</span> <span class="fu">c</span>(<span class="dv">98115</span>,<span class="dv">98103</span>,<span class="dv">98133</span>, <span class="dv">98105</span>,<span class="dv">98118</span>,<span class="dv">98125</span>,<span class="dv">98122</span>, <span class="dv">98198</span>, <span class="dv">98117</span>, <span class="dv">98155</span>),</span>
<span id="cb597-3"><a href="inferential-statistics-take-2.html#cb597-3" tabindex="-1"></a>  <span class="at">pop =</span> <span class="fu">c</span>(<span class="dv">54457</span>,<span class="dv">51878</span>,<span class="dv">50921</span>,<span class="dv">50302</span>,<span class="dv">48874</span>,<span class="dv">43993</span>,<span class="dv">41268</span>,<span class="dv">38942</span>,<span class="dv">36115</span>,<span class="dv">35550</span>)</span>
<span id="cb597-4"><a href="inferential-statistics-take-2.html#cb597-4" tabindex="-1"></a>) <span class="sc">%&gt;%</span> </span>
<span id="cb597-5"><a href="inferential-statistics-take-2.html#cb597-5" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">zip =</span> <span class="fu">as.character</span>(zip)</span>
<span id="cb597-6"><a href="inferential-statistics-take-2.html#cb597-6" tabindex="-1"></a>         , <span class="at">pop =</span> pop</span>
<span id="cb597-7"><a href="inferential-statistics-take-2.html#cb597-7" tabindex="-1"></a>         , <span class="at">popProp =</span> pop<span class="sc">/</span><span class="fu">sum</span>(pop)   ) <span class="sc">%&gt;%</span></span>
<span id="cb597-8"><a href="inferential-statistics-take-2.html#cb597-8" tabindex="-1"></a>  <span class="fu">arrange</span>(zip)</span>
<span id="cb597-9"><a href="inferential-statistics-take-2.html#cb597-9" tabindex="-1"></a>zipDF</span></code></pre></div>
<pre><code>## # A tibble: 10 × 3
##    zip     pop popProp
##    &lt;chr&gt; &lt;dbl&gt;   &lt;dbl&gt;
##  1 98103 51878  0.115 
##  2 98105 50302  0.111 
##  3 98115 54457  0.120 
##  4 98117 36115  0.0798
##  5 98118 48874  0.108 
##  6 98122 41268  0.0912
##  7 98125 43993  0.0973
##  8 98133 50921  0.113 
##  9 98155 35550  0.0786
## 10 98198 38942  0.0861</code></pre>
<p>We want to see if pet ownership is evenly distributed among these zip codes. To do this, we will use the <code>seattlepets</code> data set from the <code>openintro</code> package. As usual, be sure the check the documentation to make sure you understand what the data represents. In this case, it’s a data set detailing pet registrations in Seattle. The first 6 observations in the data set are shown below.</p>
<div class="sourceCode" id="cb599"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb599-1"><a href="inferential-statistics-take-2.html#cb599-1" tabindex="-1"></a>seattlepets <span class="sc">%&gt;%</span> </span>
<span id="cb599-2"><a href="inferential-statistics-take-2.html#cb599-2" tabindex="-1"></a>  <span class="fu">head</span>()</span></code></pre></div>
<pre><code>## # A tibble: 6 × 7
##   license_issue_date license_number animal_name species primary_breed               secondary_breed zip_code
##   &lt;date&gt;             &lt;chr&gt;          &lt;chr&gt;       &lt;chr&gt;   &lt;chr&gt;                       &lt;chr&gt;           &lt;chr&gt;   
## 1 2018-11-16         8002756        Wall-E      Dog     Mixed Breed, Medium (up to… Mix             98108   
## 2 2018-11-11         S124529        Andre       Dog     Terrier, Jack Russell       Dachshund, Sta… 98117   
## 3 2018-11-21         903793         Mac         Dog     Retriever, Labrador         &lt;NA&gt;            98136   
## 4 2018-11-23         824666         Melb        Cat     Domestic Shorthair          &lt;NA&gt;            98117   
## 5 2018-12-30         S119138        Gingersnap  Cat     Domestic Shorthair          Mix             98144   
## 6 2018-12-16         S138529        Cody        Dog     Retriever, Labrador         &lt;NA&gt;            98103</code></pre>
<p>There are many zip_codes in the data set:</p>
<div class="sourceCode" id="cb601"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb601-1"><a href="inferential-statistics-take-2.html#cb601-1" tabindex="-1"></a><span class="fu">length</span>(<span class="fu">unique</span>(seattlepets<span class="sc">$</span>zip_code))</span></code></pre></div>
<pre><code>## [1] 168</code></pre>
<p>so we need to do some manipulation to get to a place where we can make the comparison in question. First, we reformat any zip code that is of the form <code>#####-#####</code> so that it just contains the first five digits, then we will filter for only the 10 most populous zip codes, then finally count the number of licenses in each zip.</p>
<div class="sourceCode" id="cb603"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb603-1"><a href="inferential-statistics-take-2.html#cb603-1" tabindex="-1"></a>df <span class="ot">&lt;-</span> seattlepets <span class="sc">%&gt;%</span></span>
<span id="cb603-2"><a href="inferential-statistics-take-2.html#cb603-2" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">zip_code =</span> <span class="fu">str_replace</span>(zip_code, <span class="st">&#39;-[0-9]{1,}&#39;</span>, <span class="st">&#39;&#39;</span>)</span>
<span id="cb603-3"><a href="inferential-statistics-take-2.html#cb603-3" tabindex="-1"></a>         ) <span class="sc">%&gt;%</span></span>
<span id="cb603-4"><a href="inferential-statistics-take-2.html#cb603-4" tabindex="-1"></a>  <span class="fu">filter</span>(zip_code <span class="sc">%in%</span> zipDF<span class="sc">$</span>zip) <span class="sc">%&gt;%</span></span>
<span id="cb603-5"><a href="inferential-statistics-take-2.html#cb603-5" tabindex="-1"></a>  <span class="fu">group_by</span>(zip_code) <span class="sc">%&gt;%</span></span>
<span id="cb603-6"><a href="inferential-statistics-take-2.html#cb603-6" tabindex="-1"></a>  <span class="fu">summarize</span>(<span class="at">n =</span> <span class="fu">n</span>()) <span class="sc">%&gt;%</span> </span>
<span id="cb603-7"><a href="inferential-statistics-take-2.html#cb603-7" tabindex="-1"></a>  <span class="fu">arrange</span>(zip_code)</span>
<span id="cb603-8"><a href="inferential-statistics-take-2.html#cb603-8" tabindex="-1"></a></span>
<span id="cb603-9"><a href="inferential-statistics-take-2.html#cb603-9" tabindex="-1"></a>df</span></code></pre></div>
<pre><code>## # A tibble: 10 × 2
##    zip_code     n
##    &lt;chr&gt;    &lt;int&gt;
##  1 98103     4506
##  2 98105     2070
##  3 98115     4748
##  4 98117     3879
##  5 98118     2375
##  6 98122     2521
##  7 98125     2882
##  8 98133     1775
##  9 98155       28
## 10 98198        6</code></pre>
<p>Next we make sure that the zip codes are in the same order in both data sets</p>
<div class="sourceCode" id="cb605"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb605-1"><a href="inferential-statistics-take-2.html#cb605-1" tabindex="-1"></a><span class="fu">all.equal</span>(df<span class="sc">$</span>zip_code, zipDF<span class="sc">$</span>zip)</span></code></pre></div>
<pre><code>## [1] TRUE</code></pre>
<p>Now we’re ready to perform our test. If pet-ownership in different zip codes were evenly distributed, we’d expect the proportion of licenses distributed to be roughly the same as the population distribution. Thus, we want to compare the license count, the column <code>n</code> from <code>df</code> above to the population proportion <code>popProp</code> from <code>zipDF</code>. The hypothesis test we’re performing is</p>
<p><span class="math display">\[\begin{array}{cc}
H_0:\text{Pet ownership is distributed like population in Seattle} \\
H_a: \text{Pet ownership is not distributed like population in Seattle}
\end{array}
    \]</span></p>
<p>Let’s perform this test with a significance level of <span class="math inline">\(\alpha = .05\)</span>. Executing the test is now easy with <code>chisq.test</code>!</p>
<div class="sourceCode" id="cb607"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb607-1"><a href="inferential-statistics-take-2.html#cb607-1" tabindex="-1"></a>results <span class="ot">&lt;-</span> <span class="fu">chisq.test</span>(<span class="at">x =</span> df<span class="sc">$</span>n</span>
<span id="cb607-2"><a href="inferential-statistics-take-2.html#cb607-2" tabindex="-1"></a>           , <span class="at">p =</span> zipDF<span class="sc">$</span>popProp</span>
<span id="cb607-3"><a href="inferential-statistics-take-2.html#cb607-3" tabindex="-1"></a>           , <span class="at">correct =</span> F)</span>
<span id="cb607-4"><a href="inferential-statistics-take-2.html#cb607-4" tabindex="-1"></a>results </span></code></pre></div>
<pre><code>## 
##  Chi-squared test for given probabilities
## 
## data:  df$n
## X-squared = 8549.1, df = 9, p-value &lt; 2.2e-16</code></pre>
<p>Our p-value is way less than the significance level, so we reject the null and accept the research hypothesis. In other words, we have strong evidence suggesting that pet ownership/license distribution does not match the population distribution among the 10 most populous zip codes in the Seattle metro area.</p>
<p>You might wonder where the distribution deviates the most from the expectation? You can use the <code>residuals</code> element of the <code>results</code> object above to try to answer that question.</p>
<p>If obs and exp are the observed and expected counts respectively, then each residual is:</p>
<p><span class="math display">\[ \frac{\text{obs} - \text{exp}}{\sqrt{\text{exp}}} \]</span></p>
<div class="sourceCode" id="cb609"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb609-1"><a href="inferential-statistics-take-2.html#cb609-1" tabindex="-1"></a>res <span class="ot">&lt;-</span> results<span class="sc">$</span>residuals</span>
<span id="cb609-2"><a href="inferential-statistics-take-2.html#cb609-2" tabindex="-1"></a><span class="fu">names</span>(res) <span class="ot">&lt;-</span> zipDF<span class="sc">$</span>zip</span>
<span id="cb609-3"><a href="inferential-statistics-take-2.html#cb609-3" tabindex="-1"></a><span class="fu">sort</span>(res)</span></code></pre></div>
<pre><code>##      98198      98155      98133      98105      98118      98122      98125      98103      98115 
## -46.069289 -43.506938 -19.230237 -13.083768  -5.868322   5.449082   9.587784  31.180236  32.275231 
##      98117 
##  42.696200</code></pre>
<p>The output above shows us that the zip code 98198 sees way fewer licenses than we’d expect if pet ownership matched the population distribution and the zip code 98117 sees way more licensing than we would expect based on population alone.</p>
</div>
<div id="chi-squared-test-of-independence-1" class="section level3 hasAnchor" number="7.1.4">
<h3><span class="header-section-number">7.1.4</span> Chi-squared test of independence<a href="inferential-statistics-take-2.html#chi-squared-test-of-independence-1" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>Recall from the previous chapter that a chi-squared test of independence tests for an <em>association</em> between two categorical variables. No surprise, there is a built in function in <code>R</code> to perform these tests and it is again <code>chisq.test(...)</code>. The only difference from the last section is how you input data. For a goodness of fit test you</p>
<div class="sourceCode" id="cb611"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb611-1"><a href="inferential-statistics-take-2.html#cb611-1" tabindex="-1"></a>table <span class="ot">&lt;-</span> gss2010 <span class="sc">%&gt;%</span></span>
<span id="cb611-2"><a href="inferential-statistics-take-2.html#cb611-2" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">grass =</span> <span class="fu">if_else</span>(<span class="fu">is.na</span>(grass), <span class="st">&#39;NO REPLY&#39;</span>, grass)) <span class="sc">%&gt;%</span></span>
<span id="cb611-3"><a href="inferential-statistics-take-2.html#cb611-3" tabindex="-1"></a>  <span class="fu">xtabs</span>(<span class="sc">~</span>degree <span class="sc">+</span> grass, <span class="at">data =</span> .)</span>
<span id="cb611-4"><a href="inferential-statistics-take-2.html#cb611-4" tabindex="-1"></a></span>
<span id="cb611-5"><a href="inferential-statistics-take-2.html#cb611-5" tabindex="-1"></a>table</span></code></pre></div>
<pre><code>##                 grass
## degree           LEGAL NO REPLY NOT LEGAL
##   BACHELOR         119      144       112
##   GRADUATE          73       82        63
##   HIGH SCHOOL      304      390       307
##   JUNIOR COLLEGE    42       59        44
##   LT HIGH SCHOOL    65      110       130</code></pre>
<div class="sourceCode" id="cb613"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb613-1"><a href="inferential-statistics-take-2.html#cb613-1" tabindex="-1"></a>results <span class="ot">&lt;-</span> <span class="fu">chisq.test</span>(table)</span>
<span id="cb613-2"><a href="inferential-statistics-take-2.html#cb613-2" tabindex="-1"></a>results</span></code></pre></div>
<pre><code>## 
##  Pearson&#39;s Chi-squared test
## 
## data:  table
## X-squared = 22.338, df = 8, p-value = 0.004326</code></pre>
<p>Since our p-value is less than the significance level of <span class="math inline">\(\alpha = .05\)</span>, we conclude that the data imply an association between highest educational attainment and opinion on marijuana legalization. You might then wonder if you can infer what this association actually looks like to some degree. The key to this is looking at the <em>residuals</em> of this hypothesis test.</p>
<p>Recall that the chi-squared test statistic is</p>
<p><span class="math display">\[ \sum \frac{(\text{obs} - \text{exp})^2}{\text{exp}}. \]</span></p>
<p>where obs and exp represent the observed and expected counts and the sum ranges over all cells in the contingency table. The residual of a cell in a contingency table is simply</p>
<p><span class="math display">\[\text{residual} = \frac{(\text{obs} - \text{exp})}{\sqrt{\text{exp}}} \]</span></p>
<p>so a residual simply measures how far above or below the observed count is from the expected count where the difference is normalized by the expected count. Large residuals imply a large deviation from expectation, so you can think of any cell with a large residual as representing a place where the detected association between variables is more evident. We can access the residuals from our test a follows:</p>
<div class="sourceCode" id="cb615"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb615-1"><a href="inferential-statistics-take-2.html#cb615-1" tabindex="-1"></a>results<span class="sc">$</span>residuals</span></code></pre></div>
<pre><code>##                 grass
## degree                  LEGAL     NO REPLY    NOT LEGAL
##   BACHELOR        0.795903942 -0.001589914 -0.761336064
##   GRADUATE        1.083344800 -0.188315397 -0.832659358
##   HIGH SCHOOL     0.505993107  0.283830520 -0.795608394
##   JUNIOR COLLEGE -0.118711782  0.443908579 -0.371782229
##   LT HIGH SCHOOL -2.633232818 -0.659297213  3.245833866</code></pre>
<p>Most of our residuals are either around 1 or less than 1 in absolute value, except for those corresponding to people with who did not finish high school. Here we see that fewer people than expected believe that marijuana should be legalized and more think it should be illegal if the variables were actually independent.</p>
<p>Does this mean that more education <em>causes</em> one to think marijuana should be legal? Of course not! We’re simply observing an association in an observational data set and it would be a huge mistake to try to infer a causal relationship between the two variables. There are likely many confounding variables at play here.</p>
</div>
</div>
<div id="analyzing-numerical-variables-1" class="section level2 hasAnchor" number="7.2">
<h2><span class="header-section-number">7.2</span> Analyzing numerical variables<a href="inferential-statistics-take-2.html#analyzing-numerical-variables-1" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>In this section we will learn how to use R’s in-built functions to perform statistical inference for numerical variables. After the last chapter, it should come as no surprise that the bulk of our inference will be performed by a single function. For categorical variables we frequently used <code>prop.test(...)</code>; the analogous function for numerical variables is <code>t.test(...)</code>. The following subsections will guide you through the use of this function to perform inferences for single sample means, two sample mean comparisons, and paired data. We will then discuss using the function <code>aov</code> for performing ANOVA tests.</p>
<p><strong>Note:</strong> The function <code>t.test(...)</code> requires you have access to actual data, not just summary statistics. In what follows we will also discuss using the <code>tsum.test(...)</code> function from the <code>BSDA</code> package, which executes t-tests from summary statistics as well.</p>
<div id="single-sample-mean-1" class="section level3 hasAnchor" number="7.2.1">
<h3><span class="header-section-number">7.2.1</span> Single sample mean<a href="inferential-statistics-take-2.html#single-sample-mean-1" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p><strong><em>If you have a data set,</em></strong> making an inference about a numerical variable therein with <code>t.test</code> is quite easy. The basic syntax for a single numerical variable is as follows.</p>
<div class="sourceCode" id="cb617"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb617-1"><a href="inferential-statistics-take-2.html#cb617-1" tabindex="-1"></a><span class="fu">t.test</span>(</span>
<span id="cb617-2"><a href="inferential-statistics-take-2.html#cb617-2" tabindex="-1"></a>  <span class="at">x =</span> <span class="co"># a VECTOR of numerical values, typically a column of a data set.</span></span>
<span id="cb617-3"><a href="inferential-statistics-take-2.html#cb617-3" tabindex="-1"></a>  , <span class="at">mu =</span> <span class="co"># the null mean of your hypothesis test; defaults to 0.  </span></span>
<span id="cb617-4"><a href="inferential-statistics-take-2.html#cb617-4" tabindex="-1"></a>  , <span class="at">alternative =</span> <span class="co"># the type of hypothesis test to run corresponding to your alternative hypothesis; one of &quot;two.sided&quot;, &quot;less&quot;, or &quot;greater&quot;</span></span>
<span id="cb617-5"><a href="inferential-statistics-take-2.html#cb617-5" tabindex="-1"></a>  , <span class="at">conf.level =</span> <span class="co"># your confidence level as a decimal</span></span>
<span id="cb617-6"><a href="inferential-statistics-take-2.html#cb617-6" tabindex="-1"></a>)</span></code></pre></div>
<p>We will use the <code>fastfood</code> data set from the <code>openintro</code> package to demonstrate the use of this function. This data set gives the nutritional breakdown of many menu items from the following restaurants: .</p>
<div class="sourceCode" id="cb618"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb618-1"><a href="inferential-statistics-take-2.html#cb618-1" tabindex="-1"></a><span class="fu">head</span>(fastfood)</span></code></pre></div>
<pre><code>## # A tibble: 6 × 17
##   restaurant item     calories cal_fat total_fat sat_fat trans_fat cholesterol sodium total_carb fiber sugar
##   &lt;chr&gt;      &lt;chr&gt;       &lt;dbl&gt;   &lt;dbl&gt;     &lt;dbl&gt;   &lt;dbl&gt;     &lt;dbl&gt;       &lt;dbl&gt;  &lt;dbl&gt;      &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt;
## 1 Mcdonalds  Artisan…      380      60         7       2       0            95   1110         44     3    11
## 2 Mcdonalds  Single …      840     410        45      17       1.5         130   1580         62     2    18
## 3 Mcdonalds  Double …     1130     600        67      27       3           220   1920         63     3    18
## 4 Mcdonalds  Grilled…      750     280        31      10       0.5         155   1940         62     2    18
## 5 Mcdonalds  Crispy …      920     410        45      12       0.5         120   1980         81     4    18
## 6 Mcdonalds  Big Mac       540     250        28      10       1            80    950         46     3     9
## # ℹ 5 more variables: protein &lt;dbl&gt;, vit_a &lt;dbl&gt;, vit_c &lt;dbl&gt;, calcium &lt;dbl&gt;, salad &lt;chr&gt;</code></pre>
<p>Suppose we want to know the average caloric content of a burger from a fast food restaurant. Moreover, we suspect that the average burger contains more than 600 calories. To put this in the context of statistic inference, we want to calculate a confidence interval and perform a hypothesis test. Let <span class="math inline">\(\mu\)</span> denote the average calorie content of a fast food burger. Our hypothesis test is</p>
<p><span class="math display">\[\begin{array}{cc}
H_0: \mu = 600 \\
H_a: \mu &gt; 600
\end{array}
    \]</span></p>
<p>We can use the data set above to help make these inferences! We will use <code>t.test(...)</code> after massaging the data a bit. First, we’ll select all rows from <code>fastfood</code> where the item contains the word “burger” or “Burger”</p>
<div class="sourceCode" id="cb620"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb620-1"><a href="inferential-statistics-take-2.html#cb620-1" tabindex="-1"></a>burgers <span class="ot">&lt;-</span> fastfood <span class="sc">%&gt;%</span></span>
<span id="cb620-2"><a href="inferential-statistics-take-2.html#cb620-2" tabindex="-1"></a>  <span class="fu">filter</span>(<span class="fu">str_detect</span>(item, <span class="st">&#39;[bB]urger&#39;</span>)) </span>
<span id="cb620-3"><a href="inferential-statistics-take-2.html#cb620-3" tabindex="-1"></a></span>
<span id="cb620-4"><a href="inferential-statistics-take-2.html#cb620-4" tabindex="-1"></a><span class="fu">dim</span>(burgers)</span></code></pre></div>
<pre><code>## [1] 56 17</code></pre>
<p>So our data set has only 56 burgers. Let’s first execute our hypothesis test with a significance level of <span class="math inline">\(\alpha = .05\)</span> to see if our idea has any legs.</p>
<div class="sourceCode" id="cb622"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb622-1"><a href="inferential-statistics-take-2.html#cb622-1" tabindex="-1"></a>results <span class="ot">&lt;-</span> <span class="fu">t.test</span>(<span class="at">x =</span> burgers<span class="sc">$</span>calories</span>
<span id="cb622-2"><a href="inferential-statistics-take-2.html#cb622-2" tabindex="-1"></a>       , <span class="at">alternative =</span> <span class="st">&#39;greater&#39;</span></span>
<span id="cb622-3"><a href="inferential-statistics-take-2.html#cb622-3" tabindex="-1"></a>       , <span class="at">mu =</span> <span class="dv">600</span></span>
<span id="cb622-4"><a href="inferential-statistics-take-2.html#cb622-4" tabindex="-1"></a>       , <span class="at">conf.level =</span> .<span class="dv">95</span>)</span>
<span id="cb622-5"><a href="inferential-statistics-take-2.html#cb622-5" tabindex="-1"></a>results</span></code></pre></div>
<pre><code>## 
##  One Sample t-test
## 
## data:  burgers$calories
## t = 0.28482, df = 55, p-value = 0.3884
## alternative hypothesis: true mean is greater than 600
## 95 percent confidence interval:
##  552.1307      Inf
## sample estimates:
## mean of x 
##  609.8214</code></pre>
<p>Our <span class="math inline">\(p\)</span>-value is about 0.3884, greater than the significance level, so we fail to reject the null. In other words, our sample data do not provide sufficient evidence to conclude that the average burger has more than 600 calories.</p>
<p>Notice that the confidence interval reported above is one-sided to be consistent with the hypothesis test, just like the output of <code>prop.test(...)</code> when performing a one-sided hypothesis test. We can reproduce this confidence interval in a similar way. You can find the lower bound with:</p>
<div class="sourceCode" id="cb624"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb624-1"><a href="inferential-statistics-take-2.html#cb624-1" tabindex="-1"></a>t.crit <span class="ot">&lt;-</span> <span class="fu">qt</span>(.<span class="dv">05</span>, <span class="at">df =</span> <span class="dv">55</span>, <span class="at">lower.tail =</span> F)</span>
<span id="cb624-2"><a href="inferential-statistics-take-2.html#cb624-2" tabindex="-1"></a>SE <span class="ot">&lt;-</span> <span class="fu">sd</span>(burgers<span class="sc">$</span>calories)<span class="sc">/</span><span class="fu">sqrt</span>(<span class="dv">56</span>)</span>
<span id="cb624-3"><a href="inferential-statistics-take-2.html#cb624-3" tabindex="-1"></a><span class="fu">mean</span>(burgers<span class="sc">$</span>calories) <span class="sc">-</span> t.crit<span class="sc">*</span>SE</span></code></pre></div>
<pre><code>## [1] 552.1307</code></pre>
<p>The upper bounds for one-sided confidence intervals associated with one-sided lower hypothesis tests can be calculated analogously.</p>
<p>If we want standard two-sided confidence interval, we simply need to set `alternative = ‘two.sided’.</p>
<div class="sourceCode" id="cb626"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb626-1"><a href="inferential-statistics-take-2.html#cb626-1" tabindex="-1"></a>results <span class="ot">&lt;-</span> <span class="fu">t.test</span>(<span class="at">x =</span> burgers<span class="sc">$</span>calories</span>
<span id="cb626-2"><a href="inferential-statistics-take-2.html#cb626-2" tabindex="-1"></a>       , <span class="at">alternative =</span> <span class="st">&#39;two.sided&#39;</span></span>
<span id="cb626-3"><a href="inferential-statistics-take-2.html#cb626-3" tabindex="-1"></a>       , <span class="at">mu =</span> <span class="dv">600</span></span>
<span id="cb626-4"><a href="inferential-statistics-take-2.html#cb626-4" tabindex="-1"></a>       , <span class="at">conf.level =</span> .<span class="dv">95</span>)</span>
<span id="cb626-5"><a href="inferential-statistics-take-2.html#cb626-5" tabindex="-1"></a>results<span class="sc">$</span>conf.int</span></code></pre></div>
<pre><code>## [1] 540.7165 678.9263
## attr(,&quot;conf.level&quot;)
## [1] 0.95</code></pre>
<p>Thus, with 95% confidence, fast food burgers contain between about 541 and 679 calories on average.</p>
<p>Now, suppose you <strong>don’t</strong> have a data set available and only have summary statistics. This happens frequently on homework, for example. If you want to use a function similar to <code>t.test(...)</code>, you have to either write your own function (this is left as an exercise for the reader as it is beyond the scope of these notes) or install a new package called <code>BSDA</code>. This package, whose name represents “Basic Statistics and Data Analysis,” was created by Alan T. Arnholt to accompany a textbook with the same name, written by Larry J. Kitchens. In any case, remember that one must first install the package before it can be loaded into your <code>R</code> session and that it must be loaded into your <code>R</code> session before you can use any functions therein. In other words, you must run</p>
<div class="sourceCode" id="cb628"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb628-1"><a href="inferential-statistics-take-2.html#cb628-1" tabindex="-1"></a><span class="fu">install.packages</span>(<span class="st">&#39;BSDA&#39;</span>)</span></code></pre></div>
<p>once, the first time you want to use the functions, then run</p>
<div class="sourceCode" id="cb629"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb629-1"><a href="inferential-statistics-take-2.html#cb629-1" tabindex="-1"></a><span class="fu">library</span>(BSDA)</span></code></pre></div>
<p>any time you start a new <code>R</code> session and want to use this function. For a single sample t-test, the syntax for <code>t.test(...)</code> is as follows.</p>
<div class="sourceCode" id="cb630"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb630-1"><a href="inferential-statistics-take-2.html#cb630-1" tabindex="-1"></a><span class="fu">tsum.test</span>(</span>
<span id="cb630-2"><a href="inferential-statistics-take-2.html#cb630-2" tabindex="-1"></a>    <span class="at">mean.x =</span> <span class="co">#sample average</span></span>
<span id="cb630-3"><a href="inferential-statistics-take-2.html#cb630-3" tabindex="-1"></a>    , <span class="at">s.x =</span> <span class="co">#sample standard deviation</span></span>
<span id="cb630-4"><a href="inferential-statistics-take-2.html#cb630-4" tabindex="-1"></a>    , <span class="at">n.x =</span> <span class="co">#sample size</span></span>
<span id="cb630-5"><a href="inferential-statistics-take-2.html#cb630-5" tabindex="-1"></a>    , <span class="at">alternative =</span> <span class="co">#type of test to perform</span></span>
<span id="cb630-6"><a href="inferential-statistics-take-2.html#cb630-6" tabindex="-1"></a>    , <span class="at">mu =</span> <span class="co">#null mean</span></span>
<span id="cb630-7"><a href="inferential-statistics-take-2.html#cb630-7" tabindex="-1"></a>    , <span class="at">conf.level =</span> <span class="co"># confidence level as a decimal</span></span>
<span id="cb630-8"><a href="inferential-statistics-take-2.html#cb630-8" tabindex="-1"></a>)</span></code></pre></div>
<p>We will use <code>tsum.test(...)</code> to generate perform the exact same hypothesis test as above, this time inputting the sample statistics instead of the data we were interested in.</p>
<div class="sourceCode" id="cb631"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb631-1"><a href="inferential-statistics-take-2.html#cb631-1" tabindex="-1"></a>xBar <span class="ot">&lt;-</span> <span class="fu">mean</span>(burgers<span class="sc">$</span>calories)</span>
<span id="cb631-2"><a href="inferential-statistics-take-2.html#cb631-2" tabindex="-1"></a>s <span class="ot">&lt;-</span> <span class="fu">sd</span>(burgers<span class="sc">$</span>calories)</span>
<span id="cb631-3"><a href="inferential-statistics-take-2.html#cb631-3" tabindex="-1"></a>n <span class="ot">&lt;-</span> <span class="fu">dim</span>(burgers)[<span class="dv">1</span>]</span>
<span id="cb631-4"><a href="inferential-statistics-take-2.html#cb631-4" tabindex="-1"></a></span>
<span id="cb631-5"><a href="inferential-statistics-take-2.html#cb631-5" tabindex="-1"></a><span class="fu">tsum.test</span>(</span>
<span id="cb631-6"><a href="inferential-statistics-take-2.html#cb631-6" tabindex="-1"></a>  <span class="at">mean.x =</span> xBar</span>
<span id="cb631-7"><a href="inferential-statistics-take-2.html#cb631-7" tabindex="-1"></a>  , <span class="at">s.x =</span> s</span>
<span id="cb631-8"><a href="inferential-statistics-take-2.html#cb631-8" tabindex="-1"></a>  , <span class="at">n.x =</span> n</span>
<span id="cb631-9"><a href="inferential-statistics-take-2.html#cb631-9" tabindex="-1"></a>  , <span class="at">alternative =</span> <span class="st">&#39;greater&#39;</span></span>
<span id="cb631-10"><a href="inferential-statistics-take-2.html#cb631-10" tabindex="-1"></a>  , <span class="at">mu =</span> <span class="dv">600</span></span>
<span id="cb631-11"><a href="inferential-statistics-take-2.html#cb631-11" tabindex="-1"></a>  , <span class="at">conf.level =</span> .<span class="dv">95</span></span>
<span id="cb631-12"><a href="inferential-statistics-take-2.html#cb631-12" tabindex="-1"></a>)</span></code></pre></div>
<pre><code>## Warning in tsum.test(mean.x = xBar, s.x = s, n.x = n, alternative = &quot;greater&quot;, : argument &#39;var.equal&#39;
## ignored for one-sample test.</code></pre>
<pre><code>## 
##  One-sample t-Test
## 
## data:  Summarized x
## t = 0.28482, df = 55, p-value = 0.3884
## alternative hypothesis: true mean is greater than 600
## 95 percent confidence interval:
##  552.1307       NA
## sample estimates:
## mean of x 
##  609.8214</code></pre>
<p>Et Voila - the exact same results as above! You can ignore the warning about <code>var.equal</code> as it is outputting the exact behavior we want.</p>
</div>
<div id="two-sample-mean-comparison" class="section level3 hasAnchor" number="7.2.2">
<h3><span class="header-section-number">7.2.2</span> Two sample mean comparison<a href="inferential-statistics-take-2.html#two-sample-mean-comparison" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>The functions <code>t.test(...)</code> and <code>tsum.test(...)</code> also perform two-sample t-tests for us. Recall that, roughly, a two-sample t-test checks for an association between a two-valued categorical variable and a single numerical variable. With these tests you make inferences about the difference between two population averages <span class="math inline">\(\mu_1 - \mu_2\)</span> from the difference in sample averages <span class="math inline">\(\overline{x}_1 - \overline{x}_2\)</span>, so the associated confidence intervals are estimating the <em>difference</em> in population averages.</p>
<p>If you have a actual data for a two-sample t-test, use <code>t.test(...)</code> with the following syntax.</p>
<div class="sourceCode" id="cb634"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb634-1"><a href="inferential-statistics-take-2.html#cb634-1" tabindex="-1"></a><span class="fu">t.test</span>(</span>
<span id="cb634-2"><a href="inferential-statistics-take-2.html#cb634-2" tabindex="-1"></a>  <span class="at">x =</span> <span class="co">#vector of values for first group</span></span>
<span id="cb634-3"><a href="inferential-statistics-take-2.html#cb634-3" tabindex="-1"></a> , <span class="at">y =</span> <span class="co">#vector of values for the second group</span></span>
<span id="cb634-4"><a href="inferential-statistics-take-2.html#cb634-4" tabindex="-1"></a> , <span class="at">mu =</span> <span class="co">#null difference in population means, USUALLY = 0! </span></span>
<span id="cb634-5"><a href="inferential-statistics-take-2.html#cb634-5" tabindex="-1"></a> , <span class="at">alternative =</span> <span class="co"># the type of hypothesis test to run</span></span>
<span id="cb634-6"><a href="inferential-statistics-take-2.html#cb634-6" tabindex="-1"></a> , <span class="at">var.equal =</span> <span class="cn">FALSE</span> <span class="co"># we will assume the pop. variances are unequal in this class </span></span>
<span id="cb634-7"><a href="inferential-statistics-take-2.html#cb634-7" tabindex="-1"></a> , <span class="at">conf.level =</span> <span class="co"># your confidence level as a decimal</span></span>
<span id="cb634-8"><a href="inferential-statistics-take-2.html#cb634-8" tabindex="-1"></a>    )</span></code></pre></div>
<p>If you don’t have data and only have sample statistics, use <code>tsum.test(...)</code> with the following syntax.</p>
<div class="sourceCode" id="cb635"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb635-1"><a href="inferential-statistics-take-2.html#cb635-1" tabindex="-1"></a><span class="fu">tsum.test</span>(</span>
<span id="cb635-2"><a href="inferential-statistics-take-2.html#cb635-2" tabindex="-1"></a>   <span class="at">mean.x =</span> <span class="co">#sample mean from group 1 </span></span>
<span id="cb635-3"><a href="inferential-statistics-take-2.html#cb635-3" tabindex="-1"></a>  , <span class="at">s.x =</span> <span class="co">#sample std dev from group 1</span></span>
<span id="cb635-4"><a href="inferential-statistics-take-2.html#cb635-4" tabindex="-1"></a>  , <span class="at">n.x =</span> <span class="co"># sample size from group 1</span></span>
<span id="cb635-5"><a href="inferential-statistics-take-2.html#cb635-5" tabindex="-1"></a>  , <span class="at">mean.y =</span> <span class="co">#sample mean of group 2</span></span>
<span id="cb635-6"><a href="inferential-statistics-take-2.html#cb635-6" tabindex="-1"></a>  , <span class="at">s.y =</span> <span class="co"># sample std dev of group 2</span></span>
<span id="cb635-7"><a href="inferential-statistics-take-2.html#cb635-7" tabindex="-1"></a>  , <span class="at">n.y =</span> <span class="co"># sample size of group 2</span></span>
<span id="cb635-8"><a href="inferential-statistics-take-2.html#cb635-8" tabindex="-1"></a>  , <span class="at">mu =</span> <span class="co">#null difference in population means, USUALLY = 0! </span></span>
<span id="cb635-9"><a href="inferential-statistics-take-2.html#cb635-9" tabindex="-1"></a>  , <span class="at">alternative =</span> <span class="co"># the type of hypothesis test to run</span></span>
<span id="cb635-10"><a href="inferential-statistics-take-2.html#cb635-10" tabindex="-1"></a>  , <span class="at">var.equal =</span> <span class="cn">FALSE</span> <span class="co"># we will assume the pop. variances are unqequal in this class </span></span>
<span id="cb635-11"><a href="inferential-statistics-take-2.html#cb635-11" tabindex="-1"></a>  , <span class="at">conf.level =</span> <span class="co"># your confidence level as a decimal</span></span>
<span id="cb635-12"><a href="inferential-statistics-take-2.html#cb635-12" tabindex="-1"></a>)</span></code></pre></div>
<p>Let’s see these functions in action, again using the <code>fastfood</code> data set.</p>
<p>We typically think that salads are a healthier option than burgers when dining out. While “healthiness” is a complicated notion, we can compare the calorie content of these food options as a first pass at healthiness. For instance, a fast food diner may assume they are eating a lower calorie option by ordering a salad over a burger. How true is this on average? Let’s get the data ready for comparison.</p>
<div class="sourceCode" id="cb636"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb636-1"><a href="inferential-statistics-take-2.html#cb636-1" tabindex="-1"></a>burgers <span class="ot">&lt;-</span> fastfood <span class="sc">%&gt;%</span></span>
<span id="cb636-2"><a href="inferential-statistics-take-2.html#cb636-2" tabindex="-1"></a>  <span class="fu">filter</span>(<span class="fu">str_detect</span>(item, <span class="st">&#39;[bB]urger&#39;</span>)) </span>
<span id="cb636-3"><a href="inferential-statistics-take-2.html#cb636-3" tabindex="-1"></a>salads <span class="ot">&lt;-</span> fastfood <span class="sc">%&gt;%</span></span>
<span id="cb636-4"><a href="inferential-statistics-take-2.html#cb636-4" tabindex="-1"></a>  <span class="fu">filter</span>(<span class="fu">str_detect</span>(item, <span class="st">&#39;[sS]alad&#39;</span>))</span></code></pre></div>
<p>Let <span class="math inline">\(\mu_B\)</span> and <span class="math inline">\(\mu_S\)</span> denote the average calorie content of fast food burgers and salads respectively. We want to test to see if fast food salads are lower calorie than burgers, on average. This notion, as a hypothesis test is</p>
<p><span class="math display">\[\begin{array}{cc}
H_0: \mu_S - \mu_B = 0 \\
H_a: \mu_S - \mu_B &lt; 0
\end{array}
    \]</span></p>
<p>because if <span class="math inline">\(\mu_S &lt; \mu_B\)</span> then <span class="math inline">\(\mu_S - \mu_B &lt; 0\)</span>. Executing this test with <code>t.test</code> is easy! We will use a significance level of <span class="math inline">\(\alpha = .05\)</span>.</p>
<div class="sourceCode" id="cb637"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb637-1"><a href="inferential-statistics-take-2.html#cb637-1" tabindex="-1"></a>results <span class="ot">&lt;-</span> <span class="fu">t.test</span>(</span>
<span id="cb637-2"><a href="inferential-statistics-take-2.html#cb637-2" tabindex="-1"></a>  <span class="at">x =</span> salads<span class="sc">$</span>calories</span>
<span id="cb637-3"><a href="inferential-statistics-take-2.html#cb637-3" tabindex="-1"></a>  , <span class="at">y =</span> burgers<span class="sc">$</span>calories</span>
<span id="cb637-4"><a href="inferential-statistics-take-2.html#cb637-4" tabindex="-1"></a>  , <span class="at">alternative =</span> <span class="st">&#39;less&#39;</span></span>
<span id="cb637-5"><a href="inferential-statistics-take-2.html#cb637-5" tabindex="-1"></a>  , <span class="at">conf.level =</span> .<span class="dv">95</span></span>
<span id="cb637-6"><a href="inferential-statistics-take-2.html#cb637-6" tabindex="-1"></a>  , <span class="at">var.equal =</span> F</span>
<span id="cb637-7"><a href="inferential-statistics-take-2.html#cb637-7" tabindex="-1"></a>)</span>
<span id="cb637-8"><a href="inferential-statistics-take-2.html#cb637-8" tabindex="-1"></a>results</span></code></pre></div>
<pre><code>## 
##  Welch Two Sample t-test
## 
## data:  salads$calories and burgers$calories
## t = -5.5512, df = 107.05, p-value = 1.039e-07
## alternative hypothesis: true difference in means is less than 0
## 95 percent confidence interval:
##       -Inf -169.6743
## sample estimates:
## mean of x mean of y 
##  367.8125  609.8214</code></pre>
<p>With a p-value of <span class="math inline">\(p \approx 1.04 \times 10^{-7} &lt; .05 = \alpha\)</span>, we reject the null hypothesis and accept the alternative. In other words, to data provide strong evidence that, on average, fast food salads have fewer calories than burgers. Just how different are these averages? Let’s estimate the difference <span class="math inline">\(\mu_S - \mu_B\)</span> with a typical two-sided confidence interval.</p>
<div class="sourceCode" id="cb639"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb639-1"><a href="inferential-statistics-take-2.html#cb639-1" tabindex="-1"></a>results <span class="ot">&lt;-</span> <span class="fu">t.test</span>(</span>
<span id="cb639-2"><a href="inferential-statistics-take-2.html#cb639-2" tabindex="-1"></a>  <span class="at">x =</span> salads<span class="sc">$</span>calories</span>
<span id="cb639-3"><a href="inferential-statistics-take-2.html#cb639-3" tabindex="-1"></a>  , <span class="at">y =</span> burgers<span class="sc">$</span>calories</span>
<span id="cb639-4"><a href="inferential-statistics-take-2.html#cb639-4" tabindex="-1"></a>  , <span class="at">alternative =</span> <span class="st">&#39;two.sided&#39;</span></span>
<span id="cb639-5"><a href="inferential-statistics-take-2.html#cb639-5" tabindex="-1"></a>  , <span class="at">conf.level =</span> .<span class="dv">95</span></span>
<span id="cb639-6"><a href="inferential-statistics-take-2.html#cb639-6" tabindex="-1"></a>  , <span class="at">var.equal =</span> F</span>
<span id="cb639-7"><a href="inferential-statistics-take-2.html#cb639-7" tabindex="-1"></a>)</span>
<span id="cb639-8"><a href="inferential-statistics-take-2.html#cb639-8" tabindex="-1"></a>results<span class="sc">$</span>conf.int</span></code></pre></div>
<pre><code>## [1] -328.4319 -155.5859
## attr(,&quot;conf.level&quot;)
## [1] 0.95</code></pre>
<p>This calculation implies that fast food salads contain between about 155.6 and 328.4 <em>fewer</em> calories than burgers on average at the 95% confidence level.</p>
<p>As a last calculation in this section, we will perform the same hypothesis test using <code>tsum.test(...)</code> for demostration purposes. We need to first calculate all required summary statistics since they haven’t been provided.</p>
<div class="sourceCode" id="cb641"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb641-1"><a href="inferential-statistics-take-2.html#cb641-1" tabindex="-1"></a><span class="co"># sample size, sample avg, and sample std dev for salads</span></span>
<span id="cb641-2"><a href="inferential-statistics-take-2.html#cb641-2" tabindex="-1"></a>n.s <span class="ot">&lt;-</span> <span class="fu">length</span>(salads<span class="sc">$</span>calories)</span>
<span id="cb641-3"><a href="inferential-statistics-take-2.html#cb641-3" tabindex="-1"></a>mean.s <span class="ot">&lt;-</span> <span class="fu">mean</span>(salads<span class="sc">$</span>calories)</span>
<span id="cb641-4"><a href="inferential-statistics-take-2.html#cb641-4" tabindex="-1"></a>s.s <span class="ot">&lt;-</span> <span class="fu">sd</span>(salads<span class="sc">$</span>calories)</span>
<span id="cb641-5"><a href="inferential-statistics-take-2.html#cb641-5" tabindex="-1"></a><span class="co"># sample size, sample avg, and sample std dev for burgers</span></span>
<span id="cb641-6"><a href="inferential-statistics-take-2.html#cb641-6" tabindex="-1"></a>n.b <span class="ot">&lt;-</span> <span class="fu">length</span>(burgers<span class="sc">$</span>calories)</span>
<span id="cb641-7"><a href="inferential-statistics-take-2.html#cb641-7" tabindex="-1"></a>mean.b <span class="ot">&lt;-</span> <span class="fu">mean</span>(burgers<span class="sc">$</span>calories)</span>
<span id="cb641-8"><a href="inferential-statistics-take-2.html#cb641-8" tabindex="-1"></a>s.b <span class="ot">&lt;-</span> <span class="fu">sd</span>(burgers<span class="sc">$</span>calories)</span></code></pre></div>
<p>Now we need to chuck these values into <code>tsum.test(...)</code>. Here we’ll perform our initial one-sided hypothesis test.</p>
<div class="sourceCode" id="cb642"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb642-1"><a href="inferential-statistics-take-2.html#cb642-1" tabindex="-1"></a><span class="fu">tsum.test</span>(</span>
<span id="cb642-2"><a href="inferential-statistics-take-2.html#cb642-2" tabindex="-1"></a>  <span class="at">mean.x =</span> mean.s</span>
<span id="cb642-3"><a href="inferential-statistics-take-2.html#cb642-3" tabindex="-1"></a>  , <span class="at">s.x =</span> s.s</span>
<span id="cb642-4"><a href="inferential-statistics-take-2.html#cb642-4" tabindex="-1"></a>  , <span class="at">n.x =</span> n.s</span>
<span id="cb642-5"><a href="inferential-statistics-take-2.html#cb642-5" tabindex="-1"></a>  , <span class="at">mean.y =</span> mean.b</span>
<span id="cb642-6"><a href="inferential-statistics-take-2.html#cb642-6" tabindex="-1"></a>  , <span class="at">s.y =</span> s.b</span>
<span id="cb642-7"><a href="inferential-statistics-take-2.html#cb642-7" tabindex="-1"></a>  , <span class="at">n.y =</span> n.b</span>
<span id="cb642-8"><a href="inferential-statistics-take-2.html#cb642-8" tabindex="-1"></a>  , <span class="at">alternative =</span> <span class="st">&#39;less&#39;</span></span>
<span id="cb642-9"><a href="inferential-statistics-take-2.html#cb642-9" tabindex="-1"></a>  , <span class="at">conf.level =</span> .<span class="dv">95</span></span>
<span id="cb642-10"><a href="inferential-statistics-take-2.html#cb642-10" tabindex="-1"></a>  , <span class="at">var.equal =</span> F</span>
<span id="cb642-11"><a href="inferential-statistics-take-2.html#cb642-11" tabindex="-1"></a>)</span></code></pre></div>
<pre><code>## 
##  Welch Modified Two-Sample t-Test
## 
## data:  Summarized x and y
## t = -5.5512, df = 107.05, p-value = 1.039e-07
## alternative hypothesis: true difference in means is less than 0
## 95 percent confidence interval:
##         NA -169.6743
## sample estimates:
## mean of x mean of y 
##  367.8125  609.8214</code></pre>
<p>As expected, this test returns the same result. Again, <code>tsum.test(...)</code> is primarily useful when you’re doing homework or checking someone elses work and <em>only</em> have sample statistics available.</p>
</div>
<div id="paired-data-1" class="section level3 hasAnchor" number="7.2.3">
<h3><span class="header-section-number">7.2.3</span> Paired data<a href="inferential-statistics-take-2.html#paired-data-1" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>The functions <code>t.test</code> and <code>tsum.test</code> both handle paired data with ease. Recall that paired data arise whenever when there is a precise dependency between the observations of two specific variables. Paired data often comes up when looking at before/after data or when you measure two similar variables for the same individuals (reading and writing results, for instance).</p>
<p>The syntax for both functions is similar to that for a two-sample t-test. First, <code>t.test</code> runs a paired t-test with the following.</p>
<div class="sourceCode" id="cb644"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb644-1"><a href="inferential-statistics-take-2.html#cb644-1" tabindex="-1"></a><span class="fu">t.test</span>(</span>
<span id="cb644-2"><a href="inferential-statistics-take-2.html#cb644-2" tabindex="-1"></a>  <span class="at">x =</span> <span class="co">#vector of values for first group</span></span>
<span id="cb644-3"><a href="inferential-statistics-take-2.html#cb644-3" tabindex="-1"></a> , <span class="at">y =</span> <span class="co">#vector of values for the second group</span></span>
<span id="cb644-4"><a href="inferential-statistics-take-2.html#cb644-4" tabindex="-1"></a> , <span class="at">mu =</span> <span class="co">#null difference in population means, USUALLY = 0! </span></span>
<span id="cb644-5"><a href="inferential-statistics-take-2.html#cb644-5" tabindex="-1"></a> , <span class="at">alternative =</span> <span class="co"># the type of hypothesis test to run</span></span>
<span id="cb644-6"><a href="inferential-statistics-take-2.html#cb644-6" tabindex="-1"></a> , <span class="at">paired =</span> <span class="cn">TRUE</span> <span class="co"># we will assume the pop. variances are unequal in this class </span></span>
<span id="cb644-7"><a href="inferential-statistics-take-2.html#cb644-7" tabindex="-1"></a> , <span class="at">conf.level =</span> <span class="co"># your confidence level as a decimal</span></span>
<span id="cb644-8"><a href="inferential-statistics-take-2.html#cb644-8" tabindex="-1"></a>    )</span></code></pre></div>
<p>To run a paired t-test with <code>tsum.test</code> recall that the statistic you typically want to analyze when dealing with paired data is the average difference <span class="math inline">\(\mu_{diff}\)</span> and that the the mechanics of this analysis, once you’ve identified that you’re working with paired data, are identical to a single sample t-test. Thus, you can run this with</p>
<div class="sourceCode" id="cb645"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb645-1"><a href="inferential-statistics-take-2.html#cb645-1" tabindex="-1"></a><span class="fu">tsum.test</span>(</span>
<span id="cb645-2"><a href="inferential-statistics-take-2.html#cb645-2" tabindex="-1"></a>  <span class="at">mean.x =</span> <span class="co"># average sample difference</span></span>
<span id="cb645-3"><a href="inferential-statistics-take-2.html#cb645-3" tabindex="-1"></a>    , <span class="at">s.x =</span> <span class="co"># sample std dev of differences</span></span>
<span id="cb645-4"><a href="inferential-statistics-take-2.html#cb645-4" tabindex="-1"></a>    , <span class="at">n.x =</span> <span class="co"># number of differences</span></span>
<span id="cb645-5"><a href="inferential-statistics-take-2.html#cb645-5" tabindex="-1"></a>    , <span class="at">alternative =</span> <span class="co"># the type of hypothesis test to run</span></span>
<span id="cb645-6"><a href="inferential-statistics-take-2.html#cb645-6" tabindex="-1"></a>    , <span class="at">conf.level =</span> <span class="co"># your confidence level as a decimal</span></span>
<span id="cb645-7"><a href="inferential-statistics-take-2.html#cb645-7" tabindex="-1"></a>)</span></code></pre></div>
<p>As examples, we’ll use the <code>SkiExperts</code> data set that’s included in the <code>PairedData</code> package. Of course, you need to install the package before using this data set.</p>
<div class="sourceCode" id="cb646"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb646-1"><a href="inferential-statistics-take-2.html#cb646-1" tabindex="-1"></a><span class="fu">data</span>(<span class="st">&quot;SkiExperts&quot;</span>)</span>
<span id="cb646-2"><a href="inferential-statistics-take-2.html#cb646-2" tabindex="-1"></a><span class="fu">head</span>(SkiExperts)</span></code></pre></div>
<pre><code>##   Subject Actual Imaginary
## 1      S1  41.12     44.26
## 2      S2  40.21     44.80
## 3      S3  37.67     37.71
## 4      S4  38.50     37.41
## 5      S5  39.04     38.90
## 6      S6  38.91     34.14</code></pre>
<p>This data set, per the <code>R</code> documentation, “gives the actual and motor imaginary performances (time) in ski for 12 experts” where time is measured in seconds. This data set is from the paper <a href="https://pubmed.ncbi.nlm.nih.gov/22428415/">Differences in motor imagery time when predicting task duration in alpine skiers and equestrian riders</a>. The researchers essentially asked expert skiers to predict how long it would take them to ski a section of a ski course after inspecting it, then had them ski that section and recorded their times. Thus, we want to compare each skier’s predicted time to their actual time and test for a difference.</p>
<p>Since it is the same skier making the prediction, then skiing the course, these data are paired. We will look at the difference between actual and and predicted times, so <span class="math inline">\(diff = actual - predicted\)</span> and we simply want to know if there is a difference between a skiers predicted and actual time. Our hypothesis test is thus</p>
<p><span class="math display">\[\begin{array}{cc}
H_0: \mu_{diff} = 0 \\
H_a: \mu_{diff} \neq 0
\end{array}
    \]</span></p>
<p>Let’s run this test with t.test using a significance level of .05.</p>
<div class="sourceCode" id="cb648"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb648-1"><a href="inferential-statistics-take-2.html#cb648-1" tabindex="-1"></a><span class="fu">t.test</span>(<span class="at">x =</span> SkiExperts<span class="sc">$</span>Actual</span>
<span id="cb648-2"><a href="inferential-statistics-take-2.html#cb648-2" tabindex="-1"></a>       , <span class="at">y =</span> SkiExperts<span class="sc">$</span>Imaginary</span>
<span id="cb648-3"><a href="inferential-statistics-take-2.html#cb648-3" tabindex="-1"></a>       , <span class="at">mu =</span> <span class="dv">0</span></span>
<span id="cb648-4"><a href="inferential-statistics-take-2.html#cb648-4" tabindex="-1"></a>       , <span class="at">alternative =</span> <span class="st">&#39;two.sided&#39;</span></span>
<span id="cb648-5"><a href="inferential-statistics-take-2.html#cb648-5" tabindex="-1"></a>       , <span class="at">paired =</span> <span class="cn">TRUE</span></span>
<span id="cb648-6"><a href="inferential-statistics-take-2.html#cb648-6" tabindex="-1"></a>       , <span class="at">conf.level =</span> .<span class="dv">95</span></span>
<span id="cb648-7"><a href="inferential-statistics-take-2.html#cb648-7" tabindex="-1"></a>       )</span></code></pre></div>
<pre><code>## 
##  Paired t-test
## 
## data:  SkiExperts$Actual and SkiExperts$Imaginary
## t = -0.63931, df = 11, p-value = 0.5357
## alternative hypothesis: true mean difference is not equal to 0
## 95 percent confidence interval:
##  -2.384268  1.310934
## sample estimates:
## mean difference 
##      -0.5366667</code></pre>
<p>Let’s interpret the confidence interval first, then the p-value. The confidence interval tells gives us an range of values for <span class="math inline">\(\mu_{diff}\)</span>, in other words, the average difference between actual and predicted times is between -2.4 seconds and 1.3 seconds with 95% confidence. The negative value corresponds to predicted times that were shorter than actual and the positive values correspond to predicted times that are longer than actual. No surprise, with this confidence interval and a corresponding p-value of about 0.5357, we fail to reject the null. We do not have evidence that expert skiers actual ski times deviate much from their estimates on average.</p>
<p>Now let’s get at the same results using <code>tsum.test</code>. First we need the summary statistics.</p>
<div class="sourceCode" id="cb650"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb650-1"><a href="inferential-statistics-take-2.html#cb650-1" tabindex="-1"></a>AvgDiff <span class="ot">&lt;-</span> <span class="fu">mean</span>(SkiExperts<span class="sc">$</span>Actual <span class="sc">-</span> SkiExperts<span class="sc">$</span>Imaginary)</span>
<span id="cb650-2"><a href="inferential-statistics-take-2.html#cb650-2" tabindex="-1"></a>SdDiff <span class="ot">&lt;-</span> <span class="fu">sd</span>(SkiExperts<span class="sc">$</span>Actual <span class="sc">-</span> SkiExperts<span class="sc">$</span>Imaginary)</span>
<span id="cb650-3"><a href="inferential-statistics-take-2.html#cb650-3" tabindex="-1"></a>nDiff <span class="ot">&lt;-</span> <span class="fu">dim</span>(SkiExperts)[<span class="dv">1</span>] <span class="co">#number of rows = number of observations</span></span></code></pre></div>
<p>Now we use <code>tsum.test</code></p>
<div class="sourceCode" id="cb651"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb651-1"><a href="inferential-statistics-take-2.html#cb651-1" tabindex="-1"></a><span class="fu">tsum.test</span>(<span class="at">mean.x =</span> AvgDiff</span>
<span id="cb651-2"><a href="inferential-statistics-take-2.html#cb651-2" tabindex="-1"></a>          , <span class="at">s.x =</span> SdDiff</span>
<span id="cb651-3"><a href="inferential-statistics-take-2.html#cb651-3" tabindex="-1"></a>          , <span class="at">n.x =</span> nDiff</span>
<span id="cb651-4"><a href="inferential-statistics-take-2.html#cb651-4" tabindex="-1"></a>          , <span class="at">alternative =</span> <span class="st">&#39;two.sided&#39;</span></span>
<span id="cb651-5"><a href="inferential-statistics-take-2.html#cb651-5" tabindex="-1"></a>          , <span class="at">mu =</span> <span class="dv">0</span></span>
<span id="cb651-6"><a href="inferential-statistics-take-2.html#cb651-6" tabindex="-1"></a>          , <span class="at">conf.level =</span> .<span class="dv">95</span>)</span></code></pre></div>
<pre><code>## Warning in tsum.test(mean.x = AvgDiff, s.x = SdDiff, n.x = nDiff, alternative = &quot;two.sided&quot;, : argument
## &#39;var.equal&#39; ignored for one-sample test.</code></pre>
<pre><code>## 
##  One-sample t-Test
## 
## data:  Summarized x
## t = -0.63931, df = 11, p-value = 0.5357
## alternative hypothesis: true mean is not equal to 0
## 95 percent confidence interval:
##  -2.384268  1.310934
## sample estimates:
##  mean of x 
## -0.5366667</code></pre>
<p>As expected, we get the same exact results.</p>
</div>
<div id="analysis-of-variance-anova-1" class="section level3 hasAnchor" number="7.2.4">
<h3><span class="header-section-number">7.2.4</span> Analysis of variance (ANOVA)<a href="inferential-statistics-take-2.html#analysis-of-variance-anova-1" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>In the last section of this chapter, we will learn how to run ANOVA tests in <code>R</code>. Recall that ANOVA is an acronym for Analysis of Variance. Now, you might expect the command for an ANOVA test to be <code>anova(...)</code>, but you’d be wrong unfortunately. While this function does exist, it performs a different type of ANOVA analysis on different types of <code>R</code> objects (<code>anova(...)</code> compares different models built from the same data set… this is a topic beyond this class.)</p>
<p>Instead, the function we need to use is simply <code>aov(...)</code>. The input into this function requires a slightly new format: the first argument is a formula which is simply a way to express a relationship between variables. The basic format it <code>Explanatory variable ~ Response variable(s)</code>. If you have more than one response variable, you simply add the variable names together. This might seem odd in the abstract, so it might be best to see a formula in action.</p>
<p>Remember that an ANOVA test checks for an association between a categorical explanatory variable and a numerical response. If there were no association between the two variables, the average values of the numerical variable at each level of the categorical variable would be the same. If there is an association, there would have to be one average that differs from the others. Thus, the hypothesis test for ANOVA looks like</p>
<p><span class="math display">\[\begin{array}{l}
H_0: \mu_1 = \mu_2 = \cdots = \mu_k \\
H_a: \text{at least one mean differs from the others}
\end{array}
    \]</span></p>
<p>where <span class="math inline">\(\mu_i\)</span> is the average of the numerical variable in the <span class="math inline">\(i^{th}\)</span> group of the categorical variable.</p>
<p>For an example, let’s use the data set <code>gss_cat</code> from the <code>forcats</code> package (this is part of the Tidyverse, so loaded when you attach <code>tidyverse</code>). This data set gives a collection of categorical variables from the General Social Survey from the years 2000-2014.</p>
<div class="sourceCode" id="cb654"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb654-1"><a href="inferential-statistics-take-2.html#cb654-1" tabindex="-1"></a><span class="fu">head</span>(gss_cat)</span></code></pre></div>
<pre><code>## # A tibble: 6 × 9
##    year marital         age race  rincome        partyid            relig              denom         tvhours
##   &lt;int&gt; &lt;fct&gt;         &lt;int&gt; &lt;fct&gt; &lt;fct&gt;          &lt;fct&gt;              &lt;fct&gt;              &lt;fct&gt;           &lt;int&gt;
## 1  2000 Never married    26 White $8000 to 9999  Ind,near rep       Protestant         Southern bap…      12
## 2  2000 Divorced         48 White $8000 to 9999  Not str republican Protestant         Baptist-dk w…      NA
## 3  2000 Widowed          67 White Not applicable Independent        Protestant         No denominat…       2
## 4  2000 Never married    39 White Not applicable Ind,near rep       Orthodox-christian Not applicab…       4
## 5  2000 Divorced         25 White Not applicable Not str democrat   None               Not applicab…       1
## 6  2000 Married          25 White $20000 - 24999 Strong democrat    Protestant         Southern bap…      NA</code></pre>
<p>This data has many categorical variables and only 2 numerical variables: <code>age</code> and <code>tvhours</code>. In this example, let’s test to see if there is any association between a person’s religious affiliation and the amount of time they spend watching TV per day. The variable <code>tvhours</code> is missing for many observations, so we should filter out the missing values first.</p>
<div class="sourceCode" id="cb656"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb656-1"><a href="inferential-statistics-take-2.html#cb656-1" tabindex="-1"></a>df <span class="ot">&lt;-</span> gss_cat <span class="sc">%&gt;%</span></span>
<span id="cb656-2"><a href="inferential-statistics-take-2.html#cb656-2" tabindex="-1"></a>  <span class="fu">filter</span>(<span class="sc">!</span><span class="fu">is.na</span>(tvhours))</span>
<span id="cb656-3"><a href="inferential-statistics-take-2.html#cb656-3" tabindex="-1"></a><span class="fu">dim</span>(df)</span></code></pre></div>
<pre><code>## [1] 11337     9</code></pre>
<p>We have 11337 observations with non-null <code>tvhours</code>. Let’s look at the unique religions represented in this survey.</p>
<div class="sourceCode" id="cb658"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb658-1"><a href="inferential-statistics-take-2.html#cb658-1" tabindex="-1"></a><span class="fu">unique</span>(df<span class="sc">$</span>relig)</span></code></pre></div>
<pre><code>##  [1] Protestant              Orthodox-christian      None                    Christian              
##  [5] Catholic                Other                   Inter-nondenominational Jewish                 
##  [9] Native american         No answer               Buddhism                Moslem/islam           
## [13] Hinduism                Other eastern           Don&#39;t know             
## 16 Levels: No answer Don&#39;t know Inter-nondenominational Native american Christian ... Not applicable</code></pre>
<p>To simplify matters, we will lump the “Don’t know”, “None” and “No answer” replies into one category called “Atheist/agnostic”.</p>
<div class="sourceCode" id="cb660"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb660-1"><a href="inferential-statistics-take-2.html#cb660-1" tabindex="-1"></a>df <span class="ot">&lt;-</span> df <span class="sc">%&gt;%</span></span>
<span id="cb660-2"><a href="inferential-statistics-take-2.html#cb660-2" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">relig =</span> <span class="fu">case_when</span>(</span>
<span id="cb660-3"><a href="inferential-statistics-take-2.html#cb660-3" tabindex="-1"></a>    relig <span class="sc">==</span> <span class="st">&quot;Don&#39;t know&quot;</span> <span class="sc">~</span> <span class="st">&quot;Atheist/agnostic&quot;</span></span>
<span id="cb660-4"><a href="inferential-statistics-take-2.html#cb660-4" tabindex="-1"></a>    , relig <span class="sc">==</span> <span class="st">&quot;None&quot;</span> <span class="sc">~</span> <span class="st">&quot;Atheist/agnostic&quot;</span></span>
<span id="cb660-5"><a href="inferential-statistics-take-2.html#cb660-5" tabindex="-1"></a>    , relig <span class="sc">==</span> <span class="st">&quot;No answer&quot;</span> <span class="sc">~</span> <span class="st">&quot;Atheist/agnostic&quot;</span></span>
<span id="cb660-6"><a href="inferential-statistics-take-2.html#cb660-6" tabindex="-1"></a>    , <span class="at">.default =</span> relig</span>
<span id="cb660-7"><a href="inferential-statistics-take-2.html#cb660-7" tabindex="-1"></a>  ))</span></code></pre></div>
<p>Before running an ANOVA test, let’s look at some summary statistics.</p>
<div class="sourceCode" id="cb661"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb661-1"><a href="inferential-statistics-take-2.html#cb661-1" tabindex="-1"></a>df <span class="sc">%&gt;%</span></span>
<span id="cb661-2"><a href="inferential-statistics-take-2.html#cb661-2" tabindex="-1"></a>  <span class="fu">group_by</span>(relig) <span class="sc">%&gt;%</span></span>
<span id="cb661-3"><a href="inferential-statistics-take-2.html#cb661-3" tabindex="-1"></a>  <span class="fu">summarize</span>(<span class="at">n =</span> <span class="fu">n</span>()</span>
<span id="cb661-4"><a href="inferential-statistics-take-2.html#cb661-4" tabindex="-1"></a>            , <span class="at">meanTV =</span> <span class="fu">mean</span>(tvhours)</span>
<span id="cb661-5"><a href="inferential-statistics-take-2.html#cb661-5" tabindex="-1"></a>            , <span class="at">sdTV =</span> <span class="fu">sd</span>(tvhours)) <span class="sc">%&gt;%</span></span>
<span id="cb661-6"><a href="inferential-statistics-take-2.html#cb661-6" tabindex="-1"></a>  <span class="fu">arrange</span>(<span class="fu">desc</span>(n))</span></code></pre></div>
<pre><code>## # A tibble: 13 × 4
##    relig                       n meanTV  sdTV
##    &lt;chr&gt;                   &lt;int&gt;  &lt;dbl&gt; &lt;dbl&gt;
##  1 Protestant               5650   3.15  2.70
##  2 Catholic                 2695   2.96  2.35
##  3 Atheist/agnostic         1991   2.72  2.63
##  4 Christian                 391   2.79  2.50
##  5 Jewish                    189   2.52  2.07
##  6 Other                     124   2.73  2.26
##  7 Buddhism                   81   2.38  2.11
##  8 Moslem/islam               64   2.44  2.15
##  9 Inter-nondenominational    54   2.87  2.66
## 10 Hinduism                   37   1.89  1.20
## 11 Orthodox-christian         36   2.42  2.13
## 12 Native american            13   3.46  4.07
## 13 Other eastern              12   1.67  1.56</code></pre>
<p>We should assess whether or not we meet the criteria for inference.</p>
<ul>
<li><p>Are the observations independent within in and between groups? This is a reasonable assumption given that this is a random sample of GSS results over the years.</p></li>
<li><p>Are the data approximately normally distributed within each group? The variable <code>tvhours</code> is very likely right skewed since many people watch some TV but some people watch a lot. The data likely violates the normality assumption. <strong>Since we have fairly large sample sizes in each group we will ignore this though this may not be best practice!</strong></p></li>
<li><p>Is the standard deviation relatively stable across groups? There is some variability among all standard deviations, but they are not all that different… <strong>Again, this may not be best practice all of the time, but we will assume this condition is satisfied for the sake of the exercise</strong>.</p></li>
</ul>
<p>Now that we’ve checked the conditions and acknowledge that some of our assumptions are a bit shakey, we’re ready to execute the ANOVA test. Since our assumptions are shakey, we should not stake too much on the results of this test. The code chunk below demonstrates how to run the test and get a nice print out of the results. Notice that the first argument of <code>aov</code> is a formula with <code>response ~ explanatory</code>. Let’s use a significance level of 0.05.</p>
<div class="sourceCode" id="cb663"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb663-1"><a href="inferential-statistics-take-2.html#cb663-1" tabindex="-1"></a>test <span class="ot">&lt;-</span> <span class="fu">aov</span>(tvhours <span class="sc">~</span> relig, <span class="at">data =</span> df)</span>
<span id="cb663-2"><a href="inferential-statistics-take-2.html#cb663-2" tabindex="-1"></a><span class="fu">summary</span>(test)</span></code></pre></div>
<pre><code>##                Df Sum Sq Mean Sq F value   Pr(&gt;F)    
## relig          12    482   40.15   6.031 1.25e-10 ***
## Residuals   11324  75394    6.66                     
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1</code></pre>
<p>Since our p-value <span class="math inline">\(p \approx 1.3 \times 10^{-10}\)</span> is less than the significance level, we can reject the null and accept the alternative. The data provide sufficient evidence to detect an association between religion and hours spent watching TV. As usual, since this is observational data, we have no way of deciding if this is a causal relationship; we’ve merely detected a relationship (and possibly a tenuous one at that given the questionable assumptions!).</p>
<p>What does this relationship actually look like? Well, since we’re looking for differences in averages, we’d like some way of comparing them all. <code>R</code> does this automatically; it is stored in the <code>test</code> result above as <code>coefficients</code></p>
<div class="sourceCode" id="cb665"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb665-1"><a href="inferential-statistics-take-2.html#cb665-1" tabindex="-1"></a>test<span class="sc">$</span>coefficients</span></code></pre></div>
<pre><code>##                  (Intercept)                religBuddhism                religCatholic 
##                  2.718232044                 -0.335515995                  0.242064802 
##               religChristian                religHinduism religInter-nondenominational 
##                  0.072049286                 -0.826340152                  0.152138326 
##                  religJewish            religMoslem/islam         religNative american 
##                 -0.199713526                 -0.280732044                  0.743306417 
##      religOrthodox-christian                   religOther           religOther eastern 
##                 -0.301565378                  0.007574407                 -1.051565378 
##              religProtestant 
##                  0.427254681</code></pre>
<p>Notice that the religions in the output above are ordered alphabetically and that “Atheist/agnostic” is conspicuously missing. This is the religion corresponding to the intercept value. In particular, <code>(Intercept)</code> reports the average daily TV hours that Atheist/agnostic identifiers watch. The other coefficients report the change from the Atheist/agnostic group to the group in question’s average. For example, the <code>religBuddhism</code> coefficient is -0.335515995, which means that the average daily TV hours Buddhists watch is about <span class="math inline">\(2.718232044 - 0.335515995 = 2.382716\)</span>. Is this a significant difference? That’s a separate hypothesis test. However, from the results of our ANOVA test, we can conclude that some pair of religions watch different amounts of TV on average. One can use techniques that we won’t cover in this class to identify which groups deviate.</p>
<p>One obstacle that you may encounter “out in the wild” (on your homework, for instance) is that data you are provided or collect on your own is not formatted appropriately for using the <code>aov</code> function. Notice that the input requires the categorical explanatory variable to be in one column and the explanatory response to be in another. Sometimes your data is not presented in this way.</p>
<p>For example, suppose 10 students were randomly selected from FVCC, UM, and MSU at the end of STAT216 to take a statistics proficiency exam.</p>
<p>We want to compare the average exam scores for these schools. An ANOVA test is just the ticket to compare these schools. The null and alternative hypothesis are as follows.</p>
<ul>
<li><p><span class="math inline">\(H_0\)</span>: there is no association between stats proficiency and school.</p></li>
<li><p><span class="math inline">\(H_0\)</span>: there is an association between stats proficiency and school.</p></li>
</ul>
<p>Imagine that the exams are scored and you’re given the data below.</p>
<table>
<thead>
<tr class="header">
<th align="right">msu</th>
<th align="right">um</th>
<th align="right">fvcc</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="right">72</td>
<td align="right">81</td>
<td align="right">83</td>
</tr>
<tr class="even">
<td align="right">82</td>
<td align="right">84</td>
<td align="right">83</td>
</tr>
<tr class="odd">
<td align="right">87</td>
<td align="right">77</td>
<td align="right">88</td>
</tr>
<tr class="even">
<td align="right">83</td>
<td align="right">85</td>
<td align="right">78</td>
</tr>
<tr class="odd">
<td align="right">89</td>
<td align="right">80</td>
<td align="right">85</td>
</tr>
<tr class="even">
<td align="right">82</td>
<td align="right">82</td>
<td align="right">89</td>
</tr>
<tr class="odd">
<td align="right">85</td>
<td align="right">74</td>
<td align="right">81</td>
</tr>
<tr class="even">
<td align="right">83</td>
<td align="right">74</td>
<td align="right">90</td>
</tr>
<tr class="odd">
<td align="right">87</td>
<td align="right">80</td>
<td align="right">82</td>
</tr>
<tr class="even">
<td align="right">80</td>
<td align="right">84</td>
<td align="right">85</td>
</tr>
</tbody>
</table>
<p>You want to run an ANOVA test, but recognize that the numerical variable is split between 3 columns and that each column name is actually a value of the <code>school</code> variable! This will not do for using the <code>aov</code> function. The solution is reformatting the data appropriately.</p>
<p>If your data is already loaded into R, you can use the <code>pivot_longer</code> function from the <code>tidyverse</code> package. Here, our data set is called <code>df</code>. This function takes the column names and turns them into column values, just as desired.</p>
<div class="sourceCode" id="cb667"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb667-1"><a href="inferential-statistics-take-2.html#cb667-1" tabindex="-1"></a>df <span class="ot">&lt;-</span> df <span class="sc">%&gt;%</span> </span>
<span id="cb667-2"><a href="inferential-statistics-take-2.html#cb667-2" tabindex="-1"></a>  <span class="fu">pivot_longer</span>(<span class="at">cols =</span> <span class="dv">1</span><span class="sc">:</span><span class="dv">3</span> <span class="co">#selects columns 1-3 for the values</span></span>
<span id="cb667-3"><a href="inferential-statistics-take-2.html#cb667-3" tabindex="-1"></a>               , <span class="at">names_to =</span> <span class="st">&#39;school&#39;</span> <span class="co"># the name of the new column</span></span>
<span id="cb667-4"><a href="inferential-statistics-take-2.html#cb667-4" tabindex="-1"></a>               , <span class="at">values_to =</span> <span class="st">&#39;score&#39;</span>)</span>
<span id="cb667-5"><a href="inferential-statistics-take-2.html#cb667-5" tabindex="-1"></a><span class="fu">head</span>(df) <span class="co"># returns first 6 results to inspect formatting. </span></span></code></pre></div>
<pre><code>## # A tibble: 6 × 2
##   school score
##   &lt;chr&gt;  &lt;dbl&gt;
## 1 msu       72
## 2 um        81
## 3 fvcc      83
## 4 msu       82
## 5 um        84
## 6 fvcc      83</code></pre>
<p>Now, if your data isn’t in R already, you need to get in in here somehow. In an ideal world, you will have the data in a CSV file or some other spreadsheet-type file. The world is not ideal, however, so sometimes you have to enter the data into R. For the example we’re working on, I would recommend entering your data into R in the following way.</p>
<div class="sourceCode" id="cb669"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb669-1"><a href="inferential-statistics-take-2.html#cb669-1" tabindex="-1"></a><span class="co"># store each column as a list of numbers named evocatively</span></span>
<span id="cb669-2"><a href="inferential-statistics-take-2.html#cb669-2" tabindex="-1"></a>msu <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="dv">85</span>, <span class="dv">86</span>, <span class="dv">86</span>, <span class="dv">78</span>, <span class="dv">88</span>, <span class="dv">83</span>, <span class="dv">82</span>, <span class="dv">86</span>, <span class="dv">83</span>, <span class="dv">77</span>)</span>
<span id="cb669-3"><a href="inferential-statistics-take-2.html#cb669-3" tabindex="-1"></a>um <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="dv">80</span>, <span class="dv">78</span>, <span class="dv">79</span>, <span class="dv">82</span>, <span class="dv">76</span>, <span class="dv">78</span>, <span class="dv">74</span>, <span class="dv">87</span>, <span class="dv">74</span>, <span class="dv">76</span>)</span>
<span id="cb669-4"><a href="inferential-statistics-take-2.html#cb669-4" tabindex="-1"></a>fvcc <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="dv">83</span>, <span class="dv">86</span>, <span class="dv">83</span>, <span class="dv">88</span>, <span class="dv">85</span>, <span class="dv">86</span>, <span class="dv">90</span>, <span class="dv">86</span>, <span class="dv">83</span>, <span class="dv">83</span>)</span>
<span id="cb669-5"><a href="inferential-statistics-take-2.html#cb669-5" tabindex="-1"></a><span class="co"># now make one long list of numbers</span></span>
<span id="cb669-6"><a href="inferential-statistics-take-2.html#cb669-6" tabindex="-1"></a>scores <span class="ot">&lt;-</span> <span class="fu">c</span>(msu, um, fvcc)</span>
<span id="cb669-7"><a href="inferential-statistics-take-2.html#cb669-7" tabindex="-1"></a><span class="co"># now make a list of values for your categorical variable</span></span>
<span id="cb669-8"><a href="inferential-statistics-take-2.html#cb669-8" tabindex="-1"></a><span class="co"># this should respect the order of the lists you made above</span></span>
<span id="cb669-9"><a href="inferential-statistics-take-2.html#cb669-9" tabindex="-1"></a>school <span class="ot">&lt;-</span> <span class="fu">c</span>( <span class="fu">rep</span>(<span class="st">&quot;msu&quot;</span>, <span class="dv">10</span>), <span class="fu">rep</span>(<span class="st">&quot;um&quot;</span>, <span class="dv">10</span>), <span class="fu">rep</span>(<span class="st">&quot;fvcc&quot;</span>, <span class="dv">10</span>))</span>
<span id="cb669-10"><a href="inferential-statistics-take-2.html#cb669-10" tabindex="-1"></a><span class="co"># now make a dataframe/tibble with these two lists as columns.</span></span>
<span id="cb669-11"><a href="inferential-statistics-take-2.html#cb669-11" tabindex="-1"></a>df <span class="ot">&lt;-</span> <span class="fu">tibble</span>( school, scores)</span>
<span id="cb669-12"><a href="inferential-statistics-take-2.html#cb669-12" tabindex="-1"></a><span class="fu">head</span>(df)</span></code></pre></div>
<pre><code>## # A tibble: 6 × 2
##   school scores
##   &lt;chr&gt;   &lt;dbl&gt;
## 1 msu        85
## 2 msu        86
## 3 msu        86
## 4 msu        78
## 5 msu        88
## 6 msu        83</code></pre>
<p>The output of these two processes look different, but that’s only because they are sorted differently. Each score value from the MSU column in the original data set is represented in the <code>scores</code> column in a row with <code>school == 'msu'</code>.</p>
<p>Now we can easily run our desired ANOVA test</p>
<div class="sourceCode" id="cb671"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb671-1"><a href="inferential-statistics-take-2.html#cb671-1" tabindex="-1"></a>results <span class="ot">&lt;-</span> <span class="fu">aov</span>(scores <span class="sc">~</span> school, <span class="at">data =</span> df) </span>
<span id="cb671-2"><a href="inferential-statistics-take-2.html#cb671-2" tabindex="-1"></a></span>
<span id="cb671-3"><a href="inferential-statistics-take-2.html#cb671-3" tabindex="-1"></a>results <span class="sc">%&gt;%</span>  <span class="fu">summary</span>()</span></code></pre></div>
<pre><code>##             Df Sum Sq Mean Sq F value   Pr(&gt;F)    
## school       2  254.1  127.03    11.1 0.000303 ***
## Residuals   27  308.9   11.44                     
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1</code></pre>
<p>Low and behold, the data provide evidence of an association between school and statistics proficiency. We’ll look at the coefficients to try to get some idea about how the school’s averages differ.</p>
<div class="sourceCode" id="cb673"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb673-1"><a href="inferential-statistics-take-2.html#cb673-1" tabindex="-1"></a>results<span class="sc">$</span>coefficients</span></code></pre></div>
<pre><code>## (Intercept)   schoolmsu    schoolum 
##        85.3        -1.9        -6.9</code></pre>
<p>This gives a point estimate for each school’s average test score with FVCC having the highest at 85.3. According to this fabricated data, MSU and UM STAT216 students do not score as high, on average. This is, of course, completely made up.</p>
<p>On a closing note for the chapter, recall that one goal of statistical inference is detecting relationships between variables. In this chapter we encountered many different ways to do this.</p>
<ul>
<li><p>2-sample proportion tests check for associations between two (binary) categorical variables.</p></li>
<li><p>chi-squared tests of independence check for associations between two categorical variables</p></li>
<li><p>2-sample t-tests check for an association between a (binary) categorical variable and a numerical variable</p></li>
<li><p>ANOVA tests for an association between a categorical variable and a numerical variable.</p></li>
</ul>
<p>You may notice here that we have so far skipped testing for an association between two numerical variables. The main reason for this is that these associations can be somewhat more complicated than those we’ve check already. However, you’ve likely already seen one of the main tools for this task: linear regression. The next chapter discusses linear regression and describes how to use R to perform regression tasks.</p>

</div>
</div>
</div>
            </section>

          </div>
        </div>
      </div>
<a href="inferential-statistics-take-1.html" class="navigation navigation-prev " aria-label="Previous page"><i class="fa fa-angle-left"></i></a>
<a href="modeling-relationships.html" class="navigation navigation-next " aria-label="Next page"><i class="fa fa-angle-right"></i></a>
    </div>
  </div>
<script src="libs/gitbook-2.6.7/js/app.min.js"></script>
<script src="libs/gitbook-2.6.7/js/clipboard.min.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-search.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-sharing.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-fontsettings.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-bookdown.js"></script>
<script src="libs/gitbook-2.6.7/js/jquery.highlight.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-clipboard.js"></script>
<script>
gitbook.require(["gitbook"], function(gitbook) {
gitbook.start({
"sharing": {
"github": false,
"facebook": true,
"twitter": true,
"linkedin": false,
"weibo": false,
"instapaper": false,
"vk": false,
"whatsapp": false,
"all": ["facebook", "twitter", "linkedin", "weibo", "instapaper"]
},
"fontsettings": {
"theme": "white",
"family": "sans",
"size": 2
},
"edit": {
"link": "https://github.com/USERNAME/REPO/edit/BRANCH/06-inference_pt2.Rmd",
"text": "Edit"
},
"history": {
"link": null,
"text": null
},
"view": {
"link": null,
"text": null
},
"download": ["_main.pdf", "_main.epub"],
"search": {
"engine": "fuse",
"options": null
},
"toc": {
"collapse": "subsection"
}
});
});
</script>

<!-- dynamically load mathjax for compatibility with self-contained -->
<script>
  (function () {
    var script = document.createElement("script");
    script.type = "text/javascript";
    var src = "true";
    if (src === "" || src === "true") src = "https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.9/latest.js?config=TeX-MML-AM_CHTML";
    if (location.protocol !== "file:")
      if (/^https?:/.test(src))
        src = src.replace(/^https?:/, '');
    script.src = src;
    document.getElementsByTagName("head")[0].appendChild(script);
  })();
</script>
</body>

</html>
